# frozen_string_literal: true

require_relative 'spec_helper'

describe 'Scala buildpack' do
  it 'caches compiled artifacts between builds with sbt 1.x' do
    new_default_hatchet_runner('sbt-1.11.7-play-3.x-scala-2.13.x').tap do |app|
      app.deploy do
        # First build should compile everything from scratch
        expect(clean_output(app.output)).to eq(<<~OUTPUT)
          remote: -----> Scala app detected
          remote: -----> Installing Azul Zulu OpenJDK $VERSION
          remote: -----> Downloading sbt launcher 1.11.7...
          remote: -----> Setting up sbt launcher...
          remote: -----> Running: sbt compile stage
          remote:        [info] [launcher] getting org.scala-sbt sbt 1.11.7  (this may take some time)...
          remote:        [info] [launcher] getting Scala 2.12.20 (for sbt)...
          remote:        [info] welcome to sbt 1.11.7 (Azul Systems, Inc. Java $VERSION)
          remote:        [info] loading global plugins from /tmp/codon/tmp/cache/sbt_global/plugins
          remote:        [info] compiling 1 Scala source to /tmp/codon/tmp/cache/sbt_global/plugins/target/scala-2.12/sbt-1.0/classes ...
          remote:        [info] Non-compiled module 'compiler-bridge_2.12' for Scala 2.12.20. Compiling...
          remote:        [info]   Compilation completed in $DURATION.
          remote:        [info] done compiling
          remote:        [info] loading settings for project $BUILD_ID-build from plugins.sbt...
          remote:        [info] loading project definition from $BUILD_DIR/project
          remote:        [info] loading settings for project root from build.sbt...
          remote:        [info]   __              __
          remote:        [info]   \\ \\     ____   / /____ _ __  __
          remote:        [info]    \\ \\   / __ \\ / // __ `// / / /
          remote:        [info]    / /  / /_/ // // /_/ // /_/ /
          remote:        [info]   /_/  / .___//_/ \\__,_/ \\__, /
          remote:        [info]       /_/               /____/
          remote:        [info]
          remote:        [info] Version 3.0.9 running Java $VERSION
          remote:        [info]
          remote:        [info] Play is run entirely by the community. Please consider contributing and/or donating:
          remote:        [info] https://www.playframework.com/sponsors
          remote:        [info]
          remote:        [info] compiling 7 Scala sources and 1 Java source to $BUILD_DIR/target/scala-2.13/classes ...
          remote:        [info] done compiling
          remote:        [success] Total time: $DURATION, completed $DATETIME
          remote:        [info] Wrote $BUILD_DIR/target/scala-2.13/sbt-1-11-7-play-3-x-scala-2-13-x_2.13-1.0-SNAPSHOT.pom
          remote:        [success] Total time: $DURATION, completed $DATETIME
          remote: -----> Collecting sbt plugin information
          remote: -----> Collecting dependency information
          remote: -----> Copying sbt and dependencies into slug for runtime use
          remote: -----> Dropping compilation artifacts from the slug
          remote: -----> Discovering process types
          remote:        Procfile declares types     -> (none)
          remote:        Default types for buildpack -> web

          remote: -----> Compressing...
          remote:        Done: 114M
        OUTPUT

        app.commit!
        app.push!

        # Second build should use cached artifacts and doesn't recompile previously compiled application files
        expect(clean_output(app.output)).to eq(<<~OUTPUT)
          remote: -----> Scala app detected
          remote: -----> Installing Azul Zulu OpenJDK $VERSION
          remote: -----> Setting up sbt launcher...
          remote: -----> Running: sbt compile stage
          remote:        [info] welcome to sbt 1.11.7 (Azul Systems, Inc. Java $VERSION)
          remote:        [info] loading global plugins from /tmp/codon/tmp/cache/sbt_global/plugins
          remote:        [info] loading settings for project $BUILD_ID-build from plugins.sbt...
          remote:        [info] loading project definition from $BUILD_DIR/project
          remote:        [info] loading settings for project root from build.sbt...
          remote:        [info]   __              __
          remote:        [info]   \\ \\     ____   / /____ _ __  __
          remote:        [info]    \\ \\   / __ \\ / // __ `// / / /
          remote:        [info]    / /  / /_/ // // /_/ // /_/ /
          remote:        [info]   /_/  / .___//_/ \\__,_/ \\__, /
          remote:        [info]       /_/               /____/
          remote:        [info]
          remote:        [info] Version 3.0.9 running Java $VERSION
          remote:        [info]
          remote:        [info] Play is run entirely by the community. Please consider contributing and/or donating:
          remote:        [info] https://www.playframework.com/sponsors
          remote:        [info]
          remote:        [success] Total time: $DURATION, completed $DATETIME
          remote:        [info] Wrote $BUILD_DIR/target/scala-2.13/sbt-1-11-7-play-3-x-scala-2-13-x_2.13-1.0-SNAPSHOT.pom
          remote:        [success] Total time: $DURATION, completed $DATETIME
          remote: -----> Collecting sbt plugin information
          remote: -----> Collecting dependency information
          remote: -----> Copying sbt and dependencies into slug for runtime use
          remote: -----> Dropping compilation artifacts from the slug
          remote: -----> Discovering process types
          remote:        Procfile declares types     -> (none)
          remote:        Default types for buildpack -> web

          remote: -----> Compressing...
          remote:        Done: 114M
        OUTPUT
      end
    end
  end

  it 'caches compiled artifacts between builds with sbt 0.13.x' do
    new_default_hatchet_runner('sbt-0.13.18-minimal-with-native-packager').tap do |app|
      app.before_deploy do
        # Override sbt-extra's default for OpenJDK >9 and <17 to use JVMCI. Enabling JVMCI causes non-fatal
        # compile errors that bloat the build log. These compile errors are also non-deterministic so checking
        # against the output will not work reliably. We will eventually remove sbt-extras in PR #291 that will
        # make this configuration unnecessary.
        #
        # See: https://github.com/dwijnand/sbt-extras/issues/344
        app.set_config('JVM_OPTS' => '-XX:+UnlockExperimentalVMOptions -XX:-UseJVMCICompiler')
      end

      app.deploy do
        # First build should compile everything from scratch
        expect(clean_output(app.output)).to eq(<<~OUTPUT)
          remote: -----> Scala app detected
          remote: -----> Installing Azul Zulu OpenJDK $VERSION

          remote:  !     Warning: Unsupported sbt version detected.
          remote:  !
          remote:  !     This buildpack does not officially support sbt 0.13.18. You are using
          remote:  !     an end-of-life version that no longer receives security updates or bug fixes.
          remote:  !     Support for sbt 0.x was ended by the upstream sbt project on November 30, 2018.
          remote:  !
          remote:  !     Please upgrade to sbt 1.x for active support.
          remote:  !
          remote:  !     The buildpack will attempt to build your application, but compatibility
          remote:  !     is not guaranteed and may break at any time.
          remote:  !
          remote:  !     For more information:
          remote:  !     - https://web.archive.org/web/20210918065807/https://www.lightbend.com/blog/scala-sbt-127-patchnotes
          remote:  !
          remote:  !     Upgrade guide:
          remote:  !     - https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html

          remote: -----> Downloading sbt launcher 0.13.18...
          remote: -----> Setting up sbt launcher...
          remote: -----> Running: sbt compile stage
          remote:        Getting org.scala-sbt sbt 0.13.18  (this may take some time)...
          remote:        WARNING: An illegal reflective access operation has occurred
          remote:        WARNING: Illegal reflective access by org.apache.ivy.util.url.IvyAuthenticator (file:/tmp/codon/tmp/cache/sbt-launcher/sbt-launch-0.13.18.jar) to field java.net.Authenticator.theAuthenticator
          remote:        WARNING: Please consider reporting this to the maintainers of org.apache.ivy.util.url.IvyAuthenticator
          remote:        WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
          remote:        WARNING: All illegal access operations will be denied in a future release
          remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.18/jars/sbt.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#sbt;0.13.18!sbt.jar ($DURATION)
          remote:        downloading https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.10.7/scala-library-2.10.7.jar ...
          remote:        	[SUCCESSFUL ] org.scala-lang#scala-library;2.10.7!scala-library.jar ($DURATION)
          remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main/0.13.18/jars/main.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#main;0.13.18!main.jar ($DURATION)
          remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-interface/0.13.18/jars/compiler-interface.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#compiler-interface;0.13.18!compiler-interface.jar ($DURATION)
          remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/actions/0.13.18/jars/actions.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#actions;0.13.18!actions.jar ($DURATION)
          remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main-settings/0.13.18/jars/main-settings.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#main-settings;0.13.18!main-settings.jar ($DURATION)
          remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/interface/0.13.18/jars/interface.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#interface;0.13.18!interface.jar ($DURATION)
          remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/io/0.13.18/jars/io.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#io;0.13.18!io.jar ($DURATION)
          remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/ivy/0.13.18/jars/ivy.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#ivy;0.13.18!ivy.jar ($DURATION)
          remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/logging/0.13.18/jars/logging.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#logging;0.13.18!logging.jar ($DURATION)
          remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/logic/0.13.18/jars/logic.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#logic;0.13.18!logic.jar ($DURATION)
          remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/process/0.13.18/jars/process.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#process;0.13.18!process.jar ($DURATION)
          remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/run/0.13.18/jars/run.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#run;0.13.18!run.jar ($DURATION)
          remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/command/0.13.18/jars/command.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#command;0.13.18!command.jar ($DURATION)
          remote:        downloading https://repo1.maven.org/maven2/org/scala-sbt/launcher-interface/1.0.1/launcher-interface-1.0.1.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#launcher-interface;1.0.1!launcher-interface.jar ($DURATION)
          remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/classpath/0.13.18/jars/classpath.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#classpath;0.13.18!classpath.jar ($DURATION)
          remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/completion/0.13.18/jars/completion.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#completion;0.13.18!completion.jar ($DURATION)
          remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/api/0.13.18/jars/api.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#api;0.13.18!api.jar ($DURATION)
          remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-integration/0.13.18/jars/compiler-integration.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#compiler-integration;0.13.18!compiler-integration.jar ($DURATION)
          remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-ivy-integration/0.13.18/jars/compiler-ivy-integration.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#compiler-ivy-integration;0.13.18!compiler-ivy-integration.jar ($DURATION)
          remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/relation/0.13.18/jars/relation.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#relation;0.13.18!relation.jar ($DURATION)
          remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/task-system/0.13.18/jars/task-system.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#task-system;0.13.18!task-system.jar ($DURATION)
          remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/tasks/0.13.18/jars/tasks.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#tasks;0.13.18!tasks.jar ($DURATION)
          remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/tracking/0.13.18/jars/tracking.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#tracking;0.13.18!tracking.jar ($DURATION)
          remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/testing/0.13.18/jars/testing.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#testing;0.13.18!testing.jar ($DURATION)
          remote:        downloading https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.10.7/scala-compiler-2.10.7.jar ...
          remote:        	[SUCCESSFUL ] org.scala-lang#scala-compiler;2.10.7!scala-compiler.jar ($DURATION)
          remote:        downloading https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.10.7/scala-reflect-2.10.7.jar ...
          remote:        	[SUCCESSFUL ] org.scala-lang#scala-reflect;2.10.7!scala-reflect.jar ($DURATION)
          remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/control/0.13.18/jars/control.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#control;0.13.18!control.jar ($DURATION)
          remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/collections/0.13.18/jars/collections.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#collections;0.13.18!collections.jar ($DURATION)
          remote:        downloading https://repo1.maven.org/maven2/jline/jline/2.14.5/jline-2.14.5.jar ...
          remote:        	[SUCCESSFUL ] jline#jline;2.14.5!jline.jar ($DURATION)
          remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/classfile/0.13.18/jars/classfile.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#classfile;0.13.18!classfile.jar ($DURATION)
          remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/incremental-compiler/0.13.18/jars/incremental-compiler.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#incremental-compiler;0.13.18!incremental-compiler.jar ($DURATION)
          remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compile/0.13.18/jars/compile.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#compile;0.13.18!compile.jar ($DURATION)
          remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/persist/0.13.18/jars/persist.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#persist;0.13.18!persist.jar ($DURATION)
          remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-tools.sbinary/sbinary_2.10/0.4.2/jars/sbinary_2.10.jar ...
          remote:        	[SUCCESSFUL ] org.scala-tools.sbinary#sbinary_2.10;0.4.2!sbinary_2.10.jar ($DURATION)
          remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/cross/0.13.18/jars/cross.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#cross;0.13.18!cross.jar ($DURATION)
          remote:        downloading https://repo1.maven.org/maven2/org/scala-sbt/ivy/ivy/2.3.0-sbt-b18f59ea3bc914a297bb6f1a4f7fb0ace399e310/ivy-2.3.0-sbt-b18f59ea3bc914a297bb6f1a4f7fb0ace399e310.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt.ivy#ivy;2.3.0-sbt-b18f59ea3bc914a297bb6f1a4f7fb0ace399e310!ivy.jar ($DURATION)
          remote:        downloading https://repo1.maven.org/maven2/com/jcraft/jsch/0.1.50/jsch-0.1.50.jar ...
          remote:        	[SUCCESSFUL ] com.jcraft#jsch;0.1.50!jsch.jar ($DURATION)
          remote:        downloading https://repo1.maven.org/maven2/org/scala-sbt/serialization_2.10/0.1.2/serialization_2.10-0.1.2.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#serialization_2.10;0.1.2!serialization_2.10.jar ($DURATION)
          remote:        downloading https://repo1.maven.org/maven2/org/scala-lang/modules/scala-pickling_2.10/0.10.1/scala-pickling_2.10-0.10.1.jar ...
          remote:        	[SUCCESSFUL ] org.scala-lang.modules#scala-pickling_2.10;0.10.1!scala-pickling_2.10.jar ($DURATION)
          remote:        downloading https://repo1.maven.org/maven2/org/json4s/json4s-core_2.10/3.2.10/json4s-core_2.10-3.2.10.jar ...
          remote:        	[SUCCESSFUL ] org.json4s#json4s-core_2.10;3.2.10!json4s-core_2.10.jar ($DURATION)
          remote:        downloading https://repo1.maven.org/maven2/org/spire-math/jawn-parser_2.10/0.6.0/jawn-parser_2.10-0.6.0.jar ...
          remote:        	[SUCCESSFUL ] org.spire-math#jawn-parser_2.10;0.6.0!jawn-parser_2.10.jar ($DURATION)
          remote:        downloading https://repo1.maven.org/maven2/org/spire-math/json4s-support_2.10/0.6.0/json4s-support_2.10-0.6.0.jar ...
          remote:        	[SUCCESSFUL ] org.spire-math#json4s-support_2.10;0.6.0!json4s-support_2.10.jar ($DURATION)
          remote:        downloading https://repo1.maven.org/maven2/org/scalamacros/quasiquotes_2.10/2.0.1/quasiquotes_2.10-2.0.1.jar ...
          remote:        	[SUCCESSFUL ] org.scalamacros#quasiquotes_2.10;2.0.1!quasiquotes_2.10.jar ($DURATION)
          remote:        downloading https://repo1.maven.org/maven2/org/json4s/json4s-ast_2.10/3.2.10/json4s-ast_2.10-3.2.10.jar ...
          remote:        	[SUCCESSFUL ] org.json4s#json4s-ast_2.10;3.2.10!json4s-ast_2.10.jar ($DURATION)
          remote:        downloading https://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.6/paranamer-2.6.jar ...
          remote:        	[SUCCESSFUL ] com.thoughtworks.paranamer#paranamer;2.6!paranamer.jar ($DURATION)
          remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/cache/0.13.18/jars/cache.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#cache;0.13.18!cache.jar ($DURATION)
          remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/test-agent/0.13.18/jars/test-agent.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#test-agent;0.13.18!test-agent.jar ($DURATION)
          remote:        downloading https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#test-interface;1.0!test-interface.jar ($DURATION)
          remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/apply-macro/0.13.18/jars/apply-macro.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#apply-macro;0.13.18!apply-macro.jar ($DURATION)
          remote:        downloading https://repo1.maven.org/maven2/org/scala-sbt/template-resolver/0.1/template-resolver-0.1.jar ...
          remote:        	[SUCCESSFUL ] org.scala-sbt#template-resolver;0.1!template-resolver.jar ($DURATION)
          remote:        :: retrieving :: org.scala-sbt#boot-app
          remote:        	confs: [default]
          remote:        	49 artifacts copied, 0 already retrieved (17584kB/$DURATION)
          remote:        Getting Scala 2.10.7 (for sbt)...
          remote:        downloading https://repo1.maven.org/maven2/org/scala-lang/jline/2.10.7/jline-2.10.7.jar ...
          remote:        	[SUCCESSFUL ] org.scala-lang#jline;2.10.7!jline.jar ($DURATION)
          remote:        downloading https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/1.4/jansi-1.4.jar ...
          remote:        	[SUCCESSFUL ] org.fusesource.jansi#jansi;1.4!jansi.jar ($DURATION)
          remote:        :: retrieving :: org.scala-sbt#boot-scala
          remote:        	confs: [default]
          remote:        	5 artifacts copied, 0 already retrieved (24560kB/$DURATION)
          remote:        [info] Loading global plugins from /tmp/codon/tmp/cache/sbt_global/plugins
          remote:        [info] Updating {file:/tmp/codon/tmp/cache/sbt_global/plugins/}global-plugins...
          remote:        [info] Resolving org.scala-lang#scala-library;2.10.7 ...
          remote:        [info] Resolving org.scala-sbt#sbt;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#main;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#actions;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#classpath;0.13.18 ...
          remote:        [info] Resolving org.scala-lang#scala-compiler;2.10.7 ...
          remote:        [info] Resolving org.scala-lang#scala-reflect;2.10.7 ...
          remote:        [info] Resolving org.scala-sbt#interface;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#io;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#control;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#launcher-interface;1.0.1 ...
          remote:        [info] Resolving org.scala-sbt#completion;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#collections;0.13.18 ...
          remote:        [info] Resolving jline#jline;2.14.5 ...
          remote:        [info] Resolving org.scala-sbt#api;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#classfile;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#logging;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#process;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#compiler-integration;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#incremental-compiler;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#relation;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#compile;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#persist;0.13.18 ...
          remote:        [info] Resolving org.scala-tools.sbinary#sbinary_2.10;0.4.2 ...
          remote:        [info] Resolving org.scala-sbt#compiler-ivy-integration;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#ivy;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#cross;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-b18f59ea3bc914a297bb6f1a4f7fb0ace399e310 ...
          remote:        [info] Resolving com.jcraft#jsch;0.1.50 ...
          remote:        [info] Resolving org.scala-sbt#serialization_2.10;0.1.2 ...
          remote:        [info] Resolving org.scala-lang.modules#scala-pickling_2.10;0.10.1 ...
          remote:        [info] Resolving org.scalamacros#quasiquotes_2.10;2.0.1 ...
          remote:        [info] Resolving org.json4s#json4s-core_2.10;3.2.10 ...
          remote:        [info] Resolving org.json4s#json4s-ast_2.10;3.2.10 ...
          remote:        [info] Resolving com.thoughtworks.paranamer#paranamer;2.6 ...
          remote:        [info] Resolving org.spire-math#jawn-parser_2.10;0.6.0 ...
          remote:        [info] Resolving org.spire-math#json4s-support_2.10;0.6.0 ...
          remote:        [info] Resolving org.scala-sbt#run;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#task-system;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#tasks;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#tracking;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#cache;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#testing;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#test-agent;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#test-interface;1.0 ...
          remote:        [info] Resolving org.scala-sbt#main-settings;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#apply-macro;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#command;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#template-resolver;0.1 ...
          remote:        [info] Resolving org.scala-sbt#logic;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#compiler-interface;0.13.18 ...
          remote:        [info] Resolving org.scala-lang#jline;2.10.7 ...
          remote:        [info] Resolving org.fusesource.jansi#jansi;1.4 ...
          remote:        [info] Done updating.
          remote:        [info] Compiling 1 Scala source to /tmp/codon/tmp/cache/sbt_global/plugins/target/scala-2.10/sbt-0.13/classes...
          remote:        [info] 'compiler-interface' not yet compiled for Scala 2.10.7. Compiling...
          remote:        [info]   Compilation completed in $DURATION.
          remote:        [info] Loading project definition from $BUILD_DIR/project
          remote:        [info] Updating {file:$BUILD_DIR/project/}$BUILD_ID-build...
          remote:        [info] Resolving org.scala-sbt#global-plugins;0.0 ...
          remote:        [info] Resolving com.typesafe.sbt#sbt-native-packager;0.7.5-RC2 ...
          remote:        [info] Resolving com.typesafe.sbt#sbt-native-packager;0.7.5-RC2 ...
          remote:        [info] Resolving org.apache.commons#commons-compress;1.4.1 ...
          remote:        [info] Resolving org.apache.commons#commons-compress;1.4.1 ...
          remote:        [info] Resolving org.apache.commons#commons-parent;24 ...
          remote:        [info] Resolving org.apache.commons#commons-parent;24 ...
          remote:        [info] Resolving org.apache#apache;9 ...
          remote:        [info] Resolving org.apache#apache;9 ...
          remote:        [info] Resolving org.tukaani#xz;1.0 ...
          remote:        [info] Resolving org.tukaani#xz;1.0 ...
          remote:        [info] Resolving org.vafer#jdeb;1.3 ...
          remote:        [info] Resolving org.vafer#jdeb;1.3 ...
          remote:        [info] Resolving commons-io#commons-io;2.4 ...
          remote:        [info] Resolving commons-io#commons-io;2.4 ...
          remote:        [info] Resolving org.apache.commons#commons-parent;25 ...
          remote:        [info] Resolving org.apache.commons#commons-parent;25 ...
          remote:        [info] Resolving org.apache#apache;9 ...
          remote:        [info] Resolving org.apache.commons#commons-compress;1.7 ...
          remote:        [info] Resolving org.apache.commons#commons-compress;1.7 ...
          remote:        [info] Resolving org.apache.commons#commons-parent;32 ...
          remote:        [info] Resolving org.apache.commons#commons-parent;32 ...
          remote:        [info] Resolving org.apache#apache;13 ...
          remote:        [info] Resolving org.apache#apache;13 ...
          remote:        [info] Resolving org.tukaani#xz;1.4 ...
          remote:        [info] Resolving org.tukaani#xz;1.4 ...
          remote:        [info] Resolving org.apache.maven#maven-core;3.2.2 ...
          remote:        [info] Resolving org.apache.maven#maven-core;3.2.2 ...
          remote:        [info] Resolving org.apache.maven#maven;3.2.2 ...
          remote:        [info] Resolving org.apache.maven#maven;3.2.2 ...
          remote:        [info] Resolving org.apache.maven#maven-parent;24 ...
          remote:        [info] Resolving org.apache.maven#maven-parent;24 ...
          remote:        [info] Resolving org.apache#apache;14 ...
          remote:        [info] Resolving org.apache#apache;14 ...
          remote:        [info] Resolving org.apache.maven#maven-model;3.2.2 ...
          remote:        [info] Resolving org.apache.maven#maven-model;3.2.2 ...
          remote:        [info] Resolving org.apache.maven#maven;3.2.2 ...
          remote:        [info] Resolving org.codehaus.plexus#plexus-utils;3.0.17 ...
          remote:        [info] Resolving org.codehaus.plexus#plexus-utils;3.0.17 ...
          remote:        [info] Resolving org.codehaus.plexus#plexus;3.3.1 ...
          remote:        [info] Resolving org.codehaus.plexus#plexus;3.3.1 ...
          remote:        [info] Resolving org.sonatype.spice#spice-parent;17 ...
          remote:        [info] Resolving org.sonatype.spice#spice-parent;17 ...
          remote:        [info] Resolving org.sonatype.forge#forge-parent;10 ...
          remote:        [info] Resolving org.sonatype.forge#forge-parent;10 ...
          remote:        [info] Resolving org.apache.maven#maven-settings;3.2.2 ...
          remote:        [info] Resolving org.apache.maven#maven-settings;3.2.2 ...
          remote:        [info] Resolving org.apache.maven#maven;3.2.2 ...
          remote:        [info] Resolving org.apache.maven#maven-settings-builder;3.2.2 ...
          remote:        [info] Resolving org.apache.maven#maven-settings-builder;3.2.2 ...
          remote:        [info] Resolving org.apache.maven#maven;3.2.2 ...
          remote:        [info] Resolving org.codehaus.plexus#plexus-interpolation;1.19 ...
          remote:        [info] Resolving org.codehaus.plexus#plexus-interpolation;1.19 ...
          remote:        [info] Resolving org.codehaus.plexus#plexus-components;1.3.1 ...
          remote:        [info] Resolving org.codehaus.plexus#plexus-components;1.3.1 ...
          remote:        [info] Resolving org.codehaus.plexus#plexus;3.3.1 ...
          remote:        [info] Resolving org.codehaus.plexus#plexus-component-annotations;1.5.5 ...
          remote:        [info] Resolving org.codehaus.plexus#plexus-component-annotations;1.5.5 ...
          remote:        [info] Resolving org.codehaus.plexus#plexus-containers;1.5.5 ...
          remote:        [info] Resolving org.codehaus.plexus#plexus-containers;1.5.5 ...
          remote:        [info] Resolving org.codehaus.plexus#plexus;2.0.7 ...
          remote:        [info] Resolving org.codehaus.plexus#plexus;2.0.7 ...
          remote:        [info] Resolving org.sonatype.plexus#plexus-sec-dispatcher;1.3 ...
          remote:        [info] Resolving org.sonatype.plexus#plexus-sec-dispatcher;1.3 ...
          remote:        [info] Resolving org.sonatype.spice#spice-parent;12 ...
          remote:        [info] Resolving org.sonatype.spice#spice-parent;12 ...
          remote:        [info] Resolving org.sonatype.forge#forge-parent;4 ...
          remote:        [info] Resolving org.sonatype.forge#forge-parent;4 ...
          remote:        [info] Resolving org.sonatype.plexus#plexus-cipher;1.4 ...
          remote:        [info] Resolving org.sonatype.plexus#plexus-cipher;1.4 ...
          remote:        [info] Resolving org.sonatype.spice#spice-parent;12 ...
          remote:        [info] Resolving org.apache.maven#maven-repository-metadata;3.2.2 ...
          remote:        [info] Resolving org.apache.maven#maven-repository-metadata;3.2.2 ...
          remote:        [info] Resolving org.apache.maven#maven;3.2.2 ...
          remote:        [info] Resolving org.apache.maven#maven-artifact;3.2.2 ...
          remote:        [info] Resolving org.apache.maven#maven-artifact;3.2.2 ...
          remote:        [info] Resolving org.apache.maven#maven;3.2.2 ...
          remote:        [info] Resolving org.apache.maven#maven-plugin-api;3.2.2 ...
          remote:        [info] Resolving org.apache.maven#maven-plugin-api;3.2.2 ...
          remote:        [info] Resolving org.apache.maven#maven;3.2.2 ...
          remote:        [info] Resolving org.eclipse.sisu#org.eclipse.sisu.plexus;0.0.0.M5 ...
          remote:        [info] Resolving org.eclipse.sisu#org.eclipse.sisu.plexus;0.0.0.M5 ...
          remote:        [info] Resolving org.eclipse.sisu#sisu-plexus;0.0.0.M5 ...
          remote:        [info] Resolving org.eclipse.sisu#sisu-plexus;0.0.0.M5 ...
          remote:        [info] Resolving org.sonatype.oss#oss-parent;7 ...
          remote:        [info] Resolving org.sonatype.oss#oss-parent;7 ...
          remote:        [info] Resolving javax.enterprise#cdi-api;1.0 ...
          remote:        [info] Resolving javax.enterprise#cdi-api;1.0 ...
          remote:        [info] Resolving org.jboss.weld#weld-api-parent;1.0 ...
          remote:        [info] Resolving org.jboss.weld#weld-api-parent;1.0 ...
          remote:        [info] Resolving org.jboss.weld#weld-api-bom;1.0 ...
          remote:        [info] Resolving org.jboss.weld#weld-api-bom;1.0 ...
          remote:        [info] Resolving org.jboss.weld#weld-parent;6 ...
          remote:        [info] Resolving org.jboss.weld#weld-parent;6 ...
          remote:        [info] Resolving javax.annotation#jsr250-api;1.0 ...
          remote:        [info] Resolving javax.annotation#jsr250-api;1.0 ...
          remote:        [info] Resolving javax.inject#javax.inject;1 ...
          remote:        [info] Resolving javax.inject#javax.inject;1 ...
          remote:        [info] Resolving com.google.guava#guava;10.0.1 ...
          remote:        [info] Resolving com.google.guava#guava;10.0.1 ...
          remote:        [info] Resolving com.google.guava#guava-parent;10.0.1 ...
          remote:        [info] Resolving com.google.guava#guava-parent;10.0.1 ...
          remote:        [info] Resolving org.sonatype.oss#oss-parent;7 ...
          remote:        [info] Resolving com.google.code.findbugs#jsr305;1.3.9 ...
          remote:        [info] Resolving com.google.code.findbugs#jsr305;1.3.9 ...
          remote:        [info] Resolving org.sonatype.sisu#sisu-guice;3.1.0 ...
          remote:        [info] Resolving org.sonatype.sisu#sisu-guice;3.1.0 ...
          remote:        [info] Resolving org.sonatype.sisu.inject#guice-parent;3.1.0 ...
          remote:        [info] Resolving org.sonatype.sisu.inject#guice-parent;3.1.0 ...
          remote:        [info] Resolving org.sonatype.forge#forge-parent;10 ...
          remote:        [info] Resolving aopalliance#aopalliance;1.0 ...
          remote:        [info] Resolving aopalliance#aopalliance;1.0 ...
          remote:        [info] Resolving org.eclipse.sisu#org.eclipse.sisu.inject;0.0.0.M5 ...
          remote:        [info] Resolving org.eclipse.sisu#org.eclipse.sisu.inject;0.0.0.M5 ...
          remote:        [info] Resolving org.eclipse.sisu#sisu-inject;0.0.0.M5 ...
          remote:        [info] Resolving org.eclipse.sisu#sisu-inject;0.0.0.M5 ...
          remote:        [info] Resolving org.sonatype.oss#oss-parent;7 ...
          remote:        [info] Resolving org.apache.maven#maven-model-builder;3.2.2 ...
          remote:        [info] Resolving org.apache.maven#maven-model-builder;3.2.2 ...
          remote:        [info] Resolving org.apache.maven#maven;3.2.2 ...
          remote:        [info] Resolving org.apache.maven#maven-aether-provider;3.2.2 ...
          remote:        [info] Resolving org.apache.maven#maven-aether-provider;3.2.2 ...
          remote:        [info] Resolving org.apache.maven#maven;3.2.2 ...
          remote:        [info] Resolving org.eclipse.aether#aether-api;0.9.0.M2 ...
          remote:        [info] Resolving org.eclipse.aether#aether-api;0.9.0.M2 ...
          remote:        [info] Resolving org.eclipse.aether#aether;0.9.0.M2 ...
          remote:        [info] Resolving org.eclipse.aether#aether;0.9.0.M2 ...
          remote:        [info] Resolving org.eclipse.aether#aether-spi;0.9.0.M2 ...
          remote:        [info] Resolving org.eclipse.aether#aether-spi;0.9.0.M2 ...
          remote:        [info] Resolving org.eclipse.aether#aether;0.9.0.M2 ...
          remote:        [info] Resolving org.eclipse.aether#aether-util;0.9.0.M2 ...
          remote:        [info] Resolving org.eclipse.aether#aether-util;0.9.0.M2 ...
          remote:        [info] Resolving org.eclipse.aether#aether;0.9.0.M2 ...
          remote:        [info] Resolving org.eclipse.aether#aether-impl;0.9.0.M2 ...
          remote:        [info] Resolving org.eclipse.aether#aether-impl;0.9.0.M2 ...
          remote:        [info] Resolving org.eclipse.aether#aether;0.9.0.M2 ...
          remote:        [info] Resolving org.codehaus.plexus#plexus-classworlds;2.5.1 ...
          remote:        [info] Resolving org.codehaus.plexus#plexus-classworlds;2.5.1 ...
          remote:        [info] Resolving org.codehaus.plexus#plexus;3.3.1 ...
          remote:        [info] Resolving org.apache.ant#ant;1.9.3 ...
          remote:        [info] Resolving org.apache.ant#ant;1.9.3 ...
          remote:        [info] Resolving org.apache.ant#ant-parent;1.9.3 ...
          remote:        [info] Resolving org.apache.ant#ant-parent;1.9.3 ...
          remote:        [info] Resolving org.apache.ant#ant-launcher;1.9.3 ...
          remote:        [info] Resolving org.apache.ant#ant-launcher;1.9.3 ...
          remote:        [info] Resolving org.apache.ant#ant-parent;1.9.3 ...
          remote:        [info] Resolving org.bouncycastle#bcpg-jdk15on;1.51 ...
          remote:        [info] Resolving org.bouncycastle#bcpg-jdk15on;1.51 ...
          remote:        [info] Resolving org.bouncycastle#bcprov-jdk15on;1.51 ...
          remote:        [info] Resolving org.bouncycastle#bcprov-jdk15on;1.51 ...
          remote:        [info] Resolving org.scala-lang#scala-library;2.10.7 ...
          remote:        [info] Resolving org.scala-sbt#sbt;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#main;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#actions;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#classpath;0.13.18 ...
          remote:        [info] Resolving org.scala-lang#scala-compiler;2.10.7 ...
          remote:        [info] Resolving org.scala-lang#scala-reflect;2.10.7 ...
          remote:        [info] Resolving org.scala-sbt#interface;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#io;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#control;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#launcher-interface;1.0.1 ...
          remote:        [info] Resolving org.scala-sbt#completion;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#collections;0.13.18 ...
          remote:        [info] Resolving jline#jline;2.14.5 ...
          remote:        [info] Resolving org.scala-sbt#api;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#classfile;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#logging;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#process;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#compiler-integration;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#incremental-compiler;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#relation;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#compile;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#persist;0.13.18 ...
          remote:        [info] Resolving org.scala-tools.sbinary#sbinary_2.10;0.4.2 ...
          remote:        [info] Resolving org.scala-sbt#compiler-ivy-integration;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#ivy;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#cross;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-b18f59ea3bc914a297bb6f1a4f7fb0ace399e310 ...
          remote:        [info] Resolving com.jcraft#jsch;0.1.50 ...
          remote:        [info] Resolving org.scala-sbt#serialization_2.10;0.1.2 ...
          remote:        [info] Resolving org.scala-lang.modules#scala-pickling_2.10;0.10.1 ...
          remote:        [info] Resolving org.scalamacros#quasiquotes_2.10;2.0.1 ...
          remote:        [info] Resolving org.json4s#json4s-core_2.10;3.2.10 ...
          remote:        [info] Resolving org.json4s#json4s-ast_2.10;3.2.10 ...
          remote:        [info] Resolving com.thoughtworks.paranamer#paranamer;2.6 ...
          remote:        [info] Resolving org.spire-math#jawn-parser_2.10;0.6.0 ...
          remote:        [info] Resolving org.spire-math#json4s-support_2.10;0.6.0 ...
          remote:        [info] Resolving org.scala-sbt#run;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#task-system;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#tasks;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#tracking;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#cache;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#testing;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#test-agent;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#test-interface;1.0 ...
          remote:        [info] Resolving org.scala-sbt#main-settings;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#apply-macro;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#command;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#template-resolver;0.1 ...
          remote:        [info] Resolving org.scala-sbt#logic;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#compiler-interface;0.13.18 ...
          remote:        [info] Resolving org.scala-lang#jline;2.10.7 ...
          remote:        [info] Resolving org.fusesource.jansi#jansi;1.4 ...
          remote:        [info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_2.10/sbt_0.13/0.7.5-RC2/jars/sbt-native-packager.jar ...
          remote:        [info] 	[SUCCESSFUL ] com.typesafe.sbt#sbt-native-packager;0.7.5-RC2!sbt-native-packager.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/vafer/jdeb/1.3/jdeb-1.3.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.vafer#jdeb;1.3!jdeb.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/commons-io/commons-io/2.4/commons-io-2.4.jar ...
          remote:        [info] 	[SUCCESSFUL ] commons-io#commons-io;2.4!commons-io.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.7/commons-compress-1.7.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.apache.commons#commons-compress;1.7!commons-compress.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/apache/maven/maven-core/3.2.2/maven-core-3.2.2.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.apache.maven#maven-core;3.2.2!maven-core.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/apache/maven/maven-plugin-api/3.2.2/maven-plugin-api-3.2.2.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.apache.maven#maven-plugin-api;3.2.2!maven-plugin-api.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/apache/ant/ant/1.9.3/ant-1.9.3.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.apache.ant#ant;1.9.3!ant.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/bouncycastle/bcpg-jdk15on/1.51/bcpg-jdk15on-1.51.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.bouncycastle#bcpg-jdk15on;1.51!bcpg-jdk15on.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/tukaani/xz/1.4/xz-1.4.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.tukaani#xz;1.4!xz.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/apache/maven/maven-model/3.2.2/maven-model-3.2.2.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.apache.maven#maven-model;3.2.2!maven-model.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/apache/maven/maven-settings/3.2.2/maven-settings-3.2.2.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.apache.maven#maven-settings;3.2.2!maven-settings.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/apache/maven/maven-settings-builder/3.2.2/maven-settings-builder-3.2.2.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.apache.maven#maven-settings-builder;3.2.2!maven-settings-builder.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/apache/maven/maven-repository-metadata/3.2.2/maven-repository-metadata-3.2.2.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.apache.maven#maven-repository-metadata;3.2.2!maven-repository-metadata.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/apache/maven/maven-artifact/3.2.2/maven-artifact-3.2.2.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.apache.maven#maven-artifact;3.2.2!maven-artifact.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/apache/maven/maven-model-builder/3.2.2/maven-model-builder-3.2.2.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.apache.maven#maven-model-builder;3.2.2!maven-model-builder.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/apache/maven/maven-aether-provider/3.2.2/maven-aether-provider-3.2.2.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.apache.maven#maven-aether-provider;3.2.2!maven-aether-provider.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/eclipse/aether/aether-impl/0.9.0.M2/aether-impl-0.9.0.M2.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.eclipse.aether#aether-impl;0.9.0.M2!aether-impl.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/eclipse/aether/aether-api/0.9.0.M2/aether-api-0.9.0.M2.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.eclipse.aether#aether-api;0.9.0.M2!aether-api.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/eclipse/aether/aether-util/0.9.0.M2/aether-util-0.9.0.M2.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.eclipse.aether#aether-util;0.9.0.M2!aether-util.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/eclipse/sisu/org.eclipse.sisu.plexus/0.0.0.M5/org.eclipse.sisu.plexus-0.0.0.M5.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.eclipse.sisu#org.eclipse.sisu.plexus;0.0.0.M5!org.eclipse.sisu.plexus.jar(eclipse-plugin) ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-interpolation/1.19/plexus-interpolation-1.19.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.codehaus.plexus#plexus-interpolation;1.19!plexus-interpolation.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-utils/3.0.17/plexus-utils-3.0.17.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.codehaus.plexus#plexus-utils;3.0.17!plexus-utils.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-classworlds/2.5.1/plexus-classworlds-2.5.1.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.codehaus.plexus#plexus-classworlds;2.5.1!plexus-classworlds.jar(bundle) ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.codehaus.plexus#plexus-component-annotations;1.5.5!plexus-component-annotations.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.sonatype.plexus#plexus-sec-dispatcher;1.3!plexus-sec-dispatcher.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.sonatype.plexus#plexus-cipher;1.4!plexus-cipher.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar ...
          remote:        [info] 	[SUCCESSFUL ] javax.enterprise#cdi-api;1.0!cdi-api.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/com/google/guava/guava/10.0.1/guava-10.0.1.jar ...
          remote:        [info] 	[SUCCESSFUL ] com.google.guava#guava;10.0.1!guava.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/sonatype/sisu/sisu-guice/3.1.0/sisu-guice-3.1.0-no_aop.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.sonatype.sisu#sisu-guice;3.1.0!sisu-guice.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/eclipse/sisu/org.eclipse.sisu.inject/0.0.0.M5/org.eclipse.sisu.inject-0.0.0.M5.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.eclipse.sisu#org.eclipse.sisu.inject;0.0.0.M5!org.eclipse.sisu.inject.jar(eclipse-plugin) ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar ...
          remote:        [info] 	[SUCCESSFUL ] javax.annotation#jsr250-api;1.0!jsr250-api.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/javax/inject/javax.inject/1/javax.inject-1.jar ...
          remote:        [info] 	[SUCCESSFUL ] javax.inject#javax.inject;1!javax.inject.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar ...
          remote:        [info] 	[SUCCESSFUL ] com.google.code.findbugs#jsr305;1.3.9!jsr305.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/aopalliance/aopalliance/1.0/aopalliance-1.0.jar ...
          remote:        [info] 	[SUCCESSFUL ] aopalliance#aopalliance;1.0!aopalliance.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/eclipse/aether/aether-spi/0.9.0.M2/aether-spi-0.9.0.M2.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.eclipse.aether#aether-spi;0.9.0.M2!aether-spi.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/apache/ant/ant-launcher/1.9.3/ant-launcher-1.9.3.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.apache.ant#ant-launcher;1.9.3!ant-launcher.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk15on/1.51/bcprov-jdk15on-1.51.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.bouncycastle#bcprov-jdk15on;1.51!bcprov-jdk15on.jar ($DURATION)
          remote:        [info] Done updating.
          remote:        [warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
          remote:        [warn]
          remote:        [warn] 	* org.codehaus.plexus:plexus-utils:3.0.17 is selected over {2.1, 1.5.5}
          remote:        [warn] 	    +- org.apache.maven:maven-settings:3.2.2              (depends on 3.0.17)
          remote:        [warn] 	    +- org.apache.maven:maven-repository-metadata:3.2.2   (depends on 3.0.17)
          remote:        [warn] 	    +- org.apache.maven:maven-aether-provider:3.2.2       (depends on 3.0.17)
          remote:        [warn] 	    +- org.apache.maven:maven-model:3.2.2                 (depends on 3.0.17)
          remote:        [warn] 	    +- org.apache.maven:maven-core:3.2.2                  (depends on 3.0.17)
          remote:        [warn] 	    +- org.apache.maven:maven-artifact:3.2.2              (depends on 3.0.17)
          remote:        [warn] 	    +- org.apache.maven:maven-settings-builder:3.2.2      (depends on 3.0.17)
          remote:        [warn] 	    +- org.apache.maven:maven-model-builder:3.2.2         (depends on 3.0.17)
          remote:        [warn] 	    +- org.sonatype.plexus:plexus-sec-dispatcher:1.3      (depends on 1.5.5)
          remote:        [warn] 	    +- org.eclipse.sisu:org.eclipse.sisu.plexus:0.0.0.M5  (depends on 2.1)
          remote:        [warn]
          remote:        [warn] Run 'evicted' to see detailed eviction warnings
          remote:        [info] Set current project to sbt-0.13.18-minimal-with-native-packager (in build file:$BUILD_DIR/)
          remote:        [info] Updating {file:$BUILD_DIR/}$BUILD_ID...
          remote:        [info] Resolving org.scala-lang#scala-library;2.13.17 ...
          remote:        [info] Resolving org.scala-lang#scala-library;2.13.17 ...
          remote:        [info] Resolving dev.zio#zio-http_2.13;3.5.1 ...
          remote:        [info] Resolving dev.zio#zio-http_2.13;3.5.1 ...
          remote:        [info] Resolving org.scala-lang#scala-reflect;2.13.17 ...
          remote:        [info] Resolving org.scala-lang#scala-reflect;2.13.17 ...
          remote:        [info] Resolving dev.zio#zio_2.13;2.1.21 ...
          remote:        [info] Resolving dev.zio#zio_2.13;2.1.21 ...
          remote:        [info] Resolving dev.zio#zio-internal-macros_2.13;2.1.21 ...
          remote:        [info] Resolving dev.zio#zio-internal-macros_2.13;2.1.21 ...
          remote:        [info] Resolving dev.zio#zio-stacktracer_2.13;2.1.21 ...
          remote:        [info] Resolving dev.zio#zio-stacktracer_2.13;2.1.21 ...
          remote:        [info] Resolving dev.zio#izumi-reflect_2.13;3.0.6 ...
          remote:        [info] Resolving dev.zio#izumi-reflect_2.13;3.0.6 ...
          remote:        [info] Resolving dev.zio#izumi-reflect-thirdparty-boopickle-shaded_2.13;3.0.6 ...
          remote:        [info] Resolving dev.zio#izumi-reflect-thirdparty-boopickle-shaded_2.13;3.0.6 ...
          remote:        [info] Resolving org.scala-lang.modules#scala-collection-compat_2.13;2.13.0 ...
          remote:        [info] Resolving org.scala-lang.modules#scala-collection-compat_2.13;2.13.0 ...
          remote:        [info] Resolving dev.zio#zio-streams_2.13;2.1.21 ...
          remote:        [info] Resolving dev.zio#zio-streams_2.13;2.1.21 ...
          remote:        [info] Resolving dev.zio#zio-schema_2.13;1.7.4 ...
          remote:        [info] Resolving dev.zio#zio-schema_2.13;1.7.4 ...
          remote:        [info] Resolving dev.zio#zio-schema-macros_2.13;1.7.4 ...
          remote:        [info] Resolving dev.zio#zio-schema-macros_2.13;1.7.4 ...
          remote:        [info] Resolving dev.zio#zio-prelude_2.13;1.0.0-RC41 ...
          remote:        [info] Resolving dev.zio#zio-prelude_2.13;1.0.0-RC41 ...
          remote:        [info] Resolving dev.zio#zio-prelude-macros_2.13;1.0.0-RC41 ...
          remote:        [info] Resolving dev.zio#zio-prelude-macros_2.13;1.0.0-RC41 ...
          remote:        [info] Resolving dev.zio#zio-constraintless_2.13;0.3.3 ...
          remote:        [info] Resolving dev.zio#zio-constraintless_2.13;0.3.3 ...
          remote:        [info] Resolving dev.zio#zio-schema-json_2.13;1.7.4 ...
          remote:        [info] Resolving dev.zio#zio-schema-json_2.13;1.7.4 ...
          remote:        [info] Resolving dev.zio#zio-schema-derivation_2.13;1.7.4 ...
          remote:        [info] Resolving dev.zio#zio-schema-derivation_2.13;1.7.4 ...
          remote:        [info] Resolving dev.zio#zio-json_2.13;0.7.44 ...
          remote:        [info] Resolving dev.zio#zio-json_2.13;0.7.44 ...
          remote:        [info] Resolving com.softwaremill.magnolia1_2#magnolia_2.13;1.1.10 ...
          remote:        [info] Resolving com.softwaremill.magnolia1_2#magnolia_2.13;1.1.10 ...
          remote:        [info] Resolving dev.zio#zio-schema-protobuf_2.13;1.7.4 ...
          remote:        [info] Resolving dev.zio#zio-schema-protobuf_2.13;1.7.4 ...
          remote:        [info] Resolving io.netty#netty-codec-http;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-codec-http;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-parent;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-parent;4.2.6.Final ...
          remote:        [info] Resolving org.sonatype.oss#oss-parent;9 ...
          remote:        [info] Resolving io.netty#netty-common;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-common;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-parent;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-buffer;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-buffer;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-parent;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-transport;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-transport;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-parent;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-resolver;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-resolver;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-parent;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-codec-base;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-codec-base;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-parent;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-codec-compression;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-codec-compression;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-parent;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-handler;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-handler;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-parent;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-transport-native-unix-common;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-transport-native-unix-common;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-parent;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-handler-proxy;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-handler-proxy;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-parent;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-codec-socks;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-codec-socks;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-parent;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-transport-native-epoll;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-transport-native-epoll;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-parent;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-transport-classes-epoll;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-transport-classes-epoll;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-parent;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-transport-native-kqueue;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-transport-native-kqueue;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-parent;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-transport-classes-kqueue;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-transport-classes-kqueue;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-parent;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-pkitesting;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-pkitesting;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-parent;4.2.6.Final ...
          remote:        [info] Resolving org.bouncycastle#bcpkix-jdk18on;1.80 ...
          remote:        [info] Resolving org.bouncycastle#bcpkix-jdk18on;1.80 ...
          remote:        [info] Resolving org.bouncycastle#bcutil-jdk18on;[1.80,1.81) ...
          remote:        [info] Resolving org.bouncycastle#bcutil-jdk18on;[1.80,1.81) ...
          remote:        [info] Resolving org.bouncycastle#bcprov-jdk18on;1.80 ...
          remote:        [info] Resolving org.bouncycastle#bcprov-jdk18on;1.80 ...
          remote:        [info] Resolving org.scala-lang#scala-compiler;2.13.17 ...
          remote:        [info] Resolving org.scala-lang#scala-compiler;2.13.17 ...
          remote:        [info] Resolving io.github.java-diff-utils#java-diff-utils;4.16 ...
          remote:        [info] Resolving io.github.java-diff-utils#java-diff-utils;4.16 ...
          remote:        [info] Resolving io.github.java-diff-utils#java-diff-utils-parent;4.16 ...
          remote:        [info] Resolving io.github.java-diff-utils#java-diff-utils-parent;4.16 ...
          remote:        [info] Resolving org.jline#jline;3.29.0 ...
          remote:        [info] Resolving org.jline#jline;3.29.0 ...
          remote:        [info] Resolving org.jline#jline-parent;3.29.0 ...
          remote:        [info] Resolving org.jline#jline-parent;3.29.0 ...
          remote:        [info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.17/scala-library-2.13.17.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.scala-lang#scala-library;2.13.17!scala-library.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/dev/zio/zio-http_2.13/3.5.1/zio-http_2.13-3.5.1.jar ...
          remote:        [info] 	[SUCCESSFUL ] dev.zio#zio-http_2.13;3.5.1!zio-http_2.13.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.17/scala-reflect-2.13.17.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.scala-lang#scala-reflect;2.13.17!scala-reflect.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/dev/zio/zio_2.13/2.1.21/zio_2.13-2.1.21.jar ...
          remote:        [info] 	[SUCCESSFUL ] dev.zio#zio_2.13;2.1.21!zio_2.13.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/dev/zio/zio-streams_2.13/2.1.21/zio-streams_2.13-2.1.21.jar ...
          remote:        [info] 	[SUCCESSFUL ] dev.zio#zio-streams_2.13;2.1.21!zio-streams_2.13.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/dev/zio/zio-schema_2.13/1.7.4/zio-schema_2.13-1.7.4.jar ...
          remote:        [info] 	[SUCCESSFUL ] dev.zio#zio-schema_2.13;1.7.4!zio-schema_2.13.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/dev/zio/zio-schema-json_2.13/1.7.4/zio-schema-json_2.13-1.7.4.jar ...
          remote:        [info] 	[SUCCESSFUL ] dev.zio#zio-schema-json_2.13;1.7.4!zio-schema-json_2.13.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/dev/zio/zio-schema-protobuf_2.13/1.7.4/zio-schema-protobuf_2.13-1.7.4.jar ...
          remote:        [info] 	[SUCCESSFUL ] dev.zio#zio-schema-protobuf_2.13;1.7.4!zio-schema-protobuf_2.13.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.13/2.13.0/scala-collection-compat_2.13-2.13.0.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.scala-lang.modules#scala-collection-compat_2.13;2.13.0!scala-collection-compat_2.13.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/io/netty/netty-codec-http/4.2.6.Final/netty-codec-http-4.2.6.Final.jar ...
          remote:        [info] 	[SUCCESSFUL ] io.netty#netty-codec-http;4.2.6.Final!netty-codec-http.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/io/netty/netty-handler-proxy/4.2.6.Final/netty-handler-proxy-4.2.6.Final.jar ...
          remote:        [info] 	[SUCCESSFUL ] io.netty#netty-handler-proxy;4.2.6.Final!netty-handler-proxy.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/io/netty/netty-transport-native-epoll/4.2.6.Final/netty-transport-native-epoll-4.2.6.Final-linux-aarch_64.jar ...
          remote:        [info] 	[SUCCESSFUL ] io.netty#netty-transport-native-epoll;4.2.6.Final!netty-transport-native-epoll.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/io/netty/netty-transport-native-epoll/4.2.6.Final/netty-transport-native-epoll-4.2.6.Final.jar ...
          remote:        [info] 	[SUCCESSFUL ] io.netty#netty-transport-native-epoll;4.2.6.Final!netty-transport-native-epoll.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/io/netty/netty-transport-native-epoll/4.2.6.Final/netty-transport-native-epoll-4.2.6.Final-linux-x86_64.jar ...
          remote:        [info] 	[SUCCESSFUL ] io.netty#netty-transport-native-epoll;4.2.6.Final!netty-transport-native-epoll.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/io/netty/netty-transport-native-kqueue/4.2.6.Final/netty-transport-native-kqueue-4.2.6.Final-osx-aarch_64.jar ...
          remote:        [info] 	[SUCCESSFUL ] io.netty#netty-transport-native-kqueue;4.2.6.Final!netty-transport-native-kqueue.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/io/netty/netty-transport-native-kqueue/4.2.6.Final/netty-transport-native-kqueue-4.2.6.Final.jar ...
          remote:        [info] 	[SUCCESSFUL ] io.netty#netty-transport-native-kqueue;4.2.6.Final!netty-transport-native-kqueue.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/io/netty/netty-transport-native-kqueue/4.2.6.Final/netty-transport-native-kqueue-4.2.6.Final-osx-x86_64.jar ...
          remote:        [info] 	[SUCCESSFUL ] io.netty#netty-transport-native-kqueue;4.2.6.Final!netty-transport-native-kqueue.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/io/netty/netty-pkitesting/4.2.6.Final/netty-pkitesting-4.2.6.Final.jar ...
          remote:        [info] 	[SUCCESSFUL ] io.netty#netty-pkitesting;4.2.6.Final!netty-pkitesting.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/dev/zio/zio-internal-macros_2.13/2.1.21/zio-internal-macros_2.13-2.1.21.jar ...
          remote:        [info] 	[SUCCESSFUL ] dev.zio#zio-internal-macros_2.13;2.1.21!zio-internal-macros_2.13.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/dev/zio/zio-stacktracer_2.13/2.1.21/zio-stacktracer_2.13-2.1.21.jar ...
          remote:        [info] 	[SUCCESSFUL ] dev.zio#zio-stacktracer_2.13;2.1.21!zio-stacktracer_2.13.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/dev/zio/izumi-reflect_2.13/3.0.6/izumi-reflect_2.13-3.0.6.jar ...
          remote:        [info] 	[SUCCESSFUL ] dev.zio#izumi-reflect_2.13;3.0.6!izumi-reflect_2.13.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/dev/zio/izumi-reflect-thirdparty-boopickle-shaded_2.13/3.0.6/izumi-reflect-thirdparty-boopickle-shaded_2.13-3.0.6.jar ...
          remote:        [info] 	[SUCCESSFUL ] dev.zio#izumi-reflect-thirdparty-boopickle-shaded_2.13;3.0.6!izumi-reflect-thirdparty-boopickle-shaded_2.13.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/dev/zio/zio-schema-macros_2.13/1.7.4/zio-schema-macros_2.13-1.7.4.jar ...
          remote:        [info] 	[SUCCESSFUL ] dev.zio#zio-schema-macros_2.13;1.7.4!zio-schema-macros_2.13.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/dev/zio/zio-prelude_2.13/1.0.0-RC41/zio-prelude_2.13-1.0.0-RC41.jar ...
          remote:        [info] 	[SUCCESSFUL ] dev.zio#zio-prelude_2.13;1.0.0-RC41!zio-prelude_2.13.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/dev/zio/zio-constraintless_2.13/0.3.3/zio-constraintless_2.13-0.3.3.jar ...
          remote:        [info] 	[SUCCESSFUL ] dev.zio#zio-constraintless_2.13;0.3.3!zio-constraintless_2.13.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/dev/zio/zio-prelude-macros_2.13/1.0.0-RC41/zio-prelude-macros_2.13-1.0.0-RC41.jar ...
          remote:        [info] 	[SUCCESSFUL ] dev.zio#zio-prelude-macros_2.13;1.0.0-RC41!zio-prelude-macros_2.13.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/dev/zio/zio-schema-derivation_2.13/1.7.4/zio-schema-derivation_2.13-1.7.4.jar ...
          remote:        [info] 	[SUCCESSFUL ] dev.zio#zio-schema-derivation_2.13;1.7.4!zio-schema-derivation_2.13.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/dev/zio/zio-json_2.13/0.7.44/zio-json_2.13-0.7.44.jar ...
          remote:        [info] 	[SUCCESSFUL ] dev.zio#zio-json_2.13;0.7.44!zio-json_2.13.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/com/softwaremill/magnolia1_2/magnolia_2.13/1.1.10/magnolia_2.13-1.1.10.jar ...
          remote:        [info] 	[SUCCESSFUL ] com.softwaremill.magnolia1_2#magnolia_2.13;1.1.10!magnolia_2.13.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/io/netty/netty-common/4.2.6.Final/netty-common-4.2.6.Final.jar ...
          remote:        [info] 	[SUCCESSFUL ] io.netty#netty-common;4.2.6.Final!netty-common.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/io/netty/netty-buffer/4.2.6.Final/netty-buffer-4.2.6.Final.jar ...
          remote:        [info] 	[SUCCESSFUL ] io.netty#netty-buffer;4.2.6.Final!netty-buffer.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/io/netty/netty-transport/4.2.6.Final/netty-transport-4.2.6.Final.jar ...
          remote:        [info] 	[SUCCESSFUL ] io.netty#netty-transport;4.2.6.Final!netty-transport.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/io/netty/netty-codec-base/4.2.6.Final/netty-codec-base-4.2.6.Final.jar ...
          remote:        [info] 	[SUCCESSFUL ] io.netty#netty-codec-base;4.2.6.Final!netty-codec-base.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/io/netty/netty-codec-compression/4.2.6.Final/netty-codec-compression-4.2.6.Final.jar ...
          remote:        [info] 	[SUCCESSFUL ] io.netty#netty-codec-compression;4.2.6.Final!netty-codec-compression.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/io/netty/netty-handler/4.2.6.Final/netty-handler-4.2.6.Final.jar ...
          remote:        [info] 	[SUCCESSFUL ] io.netty#netty-handler;4.2.6.Final!netty-handler.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/io/netty/netty-resolver/4.2.6.Final/netty-resolver-4.2.6.Final.jar ...
          remote:        [info] 	[SUCCESSFUL ] io.netty#netty-resolver;4.2.6.Final!netty-resolver.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/io/netty/netty-transport-native-unix-common/4.2.6.Final/netty-transport-native-unix-common-4.2.6.Final.jar ...
          remote:        [info] 	[SUCCESSFUL ] io.netty#netty-transport-native-unix-common;4.2.6.Final!netty-transport-native-unix-common.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/io/netty/netty-codec-socks/4.2.6.Final/netty-codec-socks-4.2.6.Final.jar ...
          remote:        [info] 	[SUCCESSFUL ] io.netty#netty-codec-socks;4.2.6.Final!netty-codec-socks.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/io/netty/netty-transport-classes-epoll/4.2.6.Final/netty-transport-classes-epoll-4.2.6.Final.jar ...
          remote:        [info] 	[SUCCESSFUL ] io.netty#netty-transport-classes-epoll;4.2.6.Final!netty-transport-classes-epoll.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/io/netty/netty-transport-classes-kqueue/4.2.6.Final/netty-transport-classes-kqueue-4.2.6.Final.jar ...
          remote:        [info] 	[SUCCESSFUL ] io.netty#netty-transport-classes-kqueue;4.2.6.Final!netty-transport-classes-kqueue.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/bouncycastle/bcpkix-jdk18on/1.80/bcpkix-jdk18on-1.80.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.bouncycastle#bcpkix-jdk18on;1.80!bcpkix-jdk18on.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk18on/1.80/bcprov-jdk18on-1.80.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.bouncycastle#bcprov-jdk18on;1.80!bcprov-jdk18on.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/bouncycastle/bcutil-jdk18on/1.80/bcutil-jdk18on-1.80.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.bouncycastle#bcutil-jdk18on;1.80!bcutil-jdk18on.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.17/scala-compiler-2.13.17.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.scala-lang#scala-compiler;2.13.17!scala-compiler.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/io/github/java-diff-utils/java-diff-utils/4.16/java-diff-utils-4.16.jar ...
          remote:        [info] 	[SUCCESSFUL ] io.github.java-diff-utils#java-diff-utils;4.16!java-diff-utils.jar ($DURATION)
          remote:        [info] downloading https://repo1.maven.org/maven2/org/jline/jline/3.29.0/jline-3.29.0-jdk8.jar ...
          remote:        [info] 	[SUCCESSFUL ] org.jline#jline;3.29.0!jline.jar ($DURATION)
          remote:        [info] Done updating.
          remote:        [warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
          remote:        [warn]
          remote:        [warn] 	* org.bouncycastle:bcprov-jdk18on:1.80 is selected over [1.80,1.81)
          remote:        [warn] 	    +- org.bouncycastle:bcutil-jdk18on:1.80               (depends on [1.80,1.81))
          remote:        [warn] 	    +- io.netty:netty-pkitesting:4.2.6.Final              (depends on [1.80,1.81))
          remote:        [warn]
          remote:        [warn] Run 'evicted' to see detailed eviction warnings
          remote:        [info] Compiling 1 Scala source to $BUILD_DIR/target/scala-2.13/classes...
          remote:        [info] 'compiler-interface' not yet compiled for Scala 2.13.17. Compiling...
          remote:        [info]   Compilation completed in $DURATION.
          remote:        [success] Total time: $DURATION, completed $DATETIME
          remote:        [info] Wrote $BUILD_DIR/target/scala-2.13/sbt-0-13-18-minimal-with-native-packager_2.13-0.1-SNAPSHOT.pom
          remote:        [info] Packaging $BUILD_DIR/target/scala-2.13/sbt-0-13-18-minimal-with-native-packager_2.13-0.1-SNAPSHOT.jar ...
          remote:        [info] Done packaging.
          remote:        [success] Total time: $DURATION, completed $DATETIME
          remote: -----> Collecting sbt plugin information
          remote: -----> Collecting dependency information
          remote: -----> Copying sbt and dependencies into slug for runtime use
          remote: -----> Dropping compilation artifacts from the slug
          remote: -----> Discovering process types
          remote:        Procfile declares types     -> (none)
          remote:        Default types for buildpack -> web

          remote: -----> Compressing...
          remote:        Done: 99.9M
        OUTPUT

        app.commit!
        app.push!

        # Second build should use cached artifacts and doesn't recompile previously compiled application files
        expect(clean_output(app.output)).to eq(<<~OUTPUT)
          remote: -----> Scala app detected
          remote: -----> Installing Azul Zulu OpenJDK $VERSION
          
          remote:  !     Warning: Unsupported sbt version detected.
          remote:  !
          remote:  !     This buildpack does not officially support sbt 0.13.18. You are using
          remote:  !     an end-of-life version that no longer receives security updates or bug fixes.
          remote:  !     Support for sbt 0.x was ended by the upstream sbt project on November 30, 2018.
          remote:  !
          remote:  !     Please upgrade to sbt 1.x for active support.
          remote:  !
          remote:  !     The buildpack will attempt to build your application, but compatibility
          remote:  !     is not guaranteed and may break at any time.
          remote:  !
          remote:  !     For more information:
          remote:  !     - https://web.archive.org/web/20210918065807/https://www.lightbend.com/blog/scala-sbt-127-patchnotes
          remote:  !
          remote:  !     Upgrade guide:
          remote:  !     - https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html

          remote: -----> Setting up sbt launcher...
          remote: -----> Running: sbt compile stage
          remote:        [info] Loading global plugins from /tmp/codon/tmp/cache/sbt_global/plugins
          remote:        [info] Updating {file:/tmp/codon/tmp/cache/sbt_global/plugins/}global-plugins...
          remote:        WARNING: An illegal reflective access operation has occurred
          remote:        WARNING: Illegal reflective access by sbt.ivyint.ErrorMessageAuthenticator$ (file:/tmp/codon/tmp/cache/sbt_boot/scala-2.10.7/org.scala-sbt/sbt/0.13.18/ivy-0.13.18.jar) to field java.net.Authenticator.theAuthenticator
          remote:        WARNING: Please consider reporting this to the maintainers of sbt.ivyint.ErrorMessageAuthenticator$
          remote:        WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
          remote:        WARNING: All illegal access operations will be denied in a future release
          remote:        [info] Resolving org.scala-lang#scala-library;2.10.7 ...
          remote:        [info] Resolving org.scala-sbt#sbt;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#main;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#actions;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#classpath;0.13.18 ...
          remote:        [info] Resolving org.scala-lang#scala-compiler;2.10.7 ...
          remote:        [info] Resolving org.scala-lang#scala-reflect;2.10.7 ...
          remote:        [info] Resolving org.scala-sbt#interface;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#io;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#control;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#launcher-interface;1.0.1 ...
          remote:        [info] Resolving org.scala-sbt#completion;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#collections;0.13.18 ...
          remote:        [info] Resolving jline#jline;2.14.5 ...
          remote:        [info] Resolving org.scala-sbt#api;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#classfile;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#logging;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#process;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#compiler-integration;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#incremental-compiler;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#relation;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#compile;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#persist;0.13.18 ...
          remote:        [info] Resolving org.scala-tools.sbinary#sbinary_2.10;0.4.2 ...
          remote:        [info] Resolving org.scala-sbt#compiler-ivy-integration;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#ivy;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#cross;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-b18f59ea3bc914a297bb6f1a4f7fb0ace399e310 ...
          remote:        [info] Resolving com.jcraft#jsch;0.1.50 ...
          remote:        [info] Resolving org.scala-sbt#serialization_2.10;0.1.2 ...
          remote:        [info] Resolving org.scala-lang.modules#scala-pickling_2.10;0.10.1 ...
          remote:        [info] Resolving org.scalamacros#quasiquotes_2.10;2.0.1 ...
          remote:        [info] Resolving org.json4s#json4s-core_2.10;3.2.10 ...
          remote:        [info] Resolving org.json4s#json4s-ast_2.10;3.2.10 ...
          remote:        [info] Resolving com.thoughtworks.paranamer#paranamer;2.6 ...
          remote:        [info] Resolving org.spire-math#jawn-parser_2.10;0.6.0 ...
          remote:        [info] Resolving org.spire-math#json4s-support_2.10;0.6.0 ...
          remote:        [info] Resolving org.scala-sbt#run;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#task-system;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#tasks;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#tracking;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#cache;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#testing;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#test-agent;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#test-interface;1.0 ...
          remote:        [info] Resolving org.scala-sbt#main-settings;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#apply-macro;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#command;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#template-resolver;0.1 ...
          remote:        [info] Resolving org.scala-sbt#logic;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#compiler-interface;0.13.18 ...
          remote:        [info] Resolving org.scala-lang#jline;2.10.7 ...
          remote:        [info] Resolving org.fusesource.jansi#jansi;1.4 ...
          remote:        [info] Done updating.
          remote:        [info] Compiling 1 Scala source to /tmp/codon/tmp/cache/sbt_global/plugins/target/scala-2.10/sbt-0.13/classes...
          remote:        [info] Loading project definition from $BUILD_DIR/project
          remote:        [info] Updating {file:$BUILD_DIR/project/}$BUILD_ID-build...
          remote:        [info] Resolving org.scala-sbt#global-plugins;0.0 ...
          remote:        [info] Resolving com.typesafe.sbt#sbt-native-packager;0.7.5-RC2 ...
          remote:        [info] Resolving org.apache.commons#commons-compress;1.4.1 ...
          remote:        [info] Resolving org.tukaani#xz;1.0 ...
          remote:        [info] Resolving org.vafer#jdeb;1.3 ...
          remote:        [info] Resolving commons-io#commons-io;2.4 ...
          remote:        [info] Resolving org.apache.commons#commons-compress;1.7 ...
          remote:        [info] Resolving org.tukaani#xz;1.4 ...
          remote:        [info] Resolving org.apache.maven#maven-core;3.2.2 ...
          remote:        [info] Resolving org.apache.maven#maven-model;3.2.2 ...
          remote:        [info] Resolving org.codehaus.plexus#plexus-utils;3.0.17 ...
          remote:        [info] Resolving org.apache.maven#maven-settings;3.2.2 ...
          remote:        [info] Resolving org.apache.maven#maven-settings-builder;3.2.2 ...
          remote:        [info] Resolving org.codehaus.plexus#plexus-interpolation;1.19 ...
          remote:        [info] Resolving org.codehaus.plexus#plexus-component-annotations;1.5.5 ...
          remote:        [info] Resolving org.sonatype.plexus#plexus-sec-dispatcher;1.3 ...
          remote:        [info] Resolving org.sonatype.plexus#plexus-cipher;1.4 ...
          remote:        [info] Resolving org.apache.maven#maven-repository-metadata;3.2.2 ...
          remote:        [info] Resolving org.apache.maven#maven-artifact;3.2.2 ...
          remote:        [info] Resolving org.apache.maven#maven-plugin-api;3.2.2 ...
          remote:        [info] Resolving org.eclipse.sisu#org.eclipse.sisu.plexus;0.0.0.M5 ...
          remote:        [info] Resolving javax.enterprise#cdi-api;1.0 ...
          remote:        [info] Resolving javax.annotation#jsr250-api;1.0 ...
          remote:        [info] Resolving javax.inject#javax.inject;1 ...
          remote:        [info] Resolving com.google.guava#guava;10.0.1 ...
          remote:        [info] Resolving com.google.code.findbugs#jsr305;1.3.9 ...
          remote:        [info] Resolving org.sonatype.sisu#sisu-guice;3.1.0 ...
          remote:        [info] Resolving aopalliance#aopalliance;1.0 ...
          remote:        [info] Resolving org.eclipse.sisu#org.eclipse.sisu.inject;0.0.0.M5 ...
          remote:        [info] Resolving org.apache.maven#maven-model-builder;3.2.2 ...
          remote:        [info] Resolving org.apache.maven#maven-aether-provider;3.2.2 ...
          remote:        [info] Resolving org.eclipse.aether#aether-api;0.9.0.M2 ...
          remote:        [info] Resolving org.eclipse.aether#aether-spi;0.9.0.M2 ...
          remote:        [info] Resolving org.eclipse.aether#aether-util;0.9.0.M2 ...
          remote:        [info] Resolving org.eclipse.aether#aether-impl;0.9.0.M2 ...
          remote:        [info] Resolving org.codehaus.plexus#plexus-classworlds;2.5.1 ...
          remote:        [info] Resolving org.apache.ant#ant;1.9.3 ...
          remote:        [info] Resolving org.apache.ant#ant-launcher;1.9.3 ...
          remote:        [info] Resolving org.bouncycastle#bcpg-jdk15on;1.51 ...
          remote:        [info] Resolving org.bouncycastle#bcprov-jdk15on;1.51 ...
          remote:        [info] Resolving org.scala-lang#scala-library;2.10.7 ...
          remote:        [info] Resolving org.scala-sbt#sbt;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#main;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#actions;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#classpath;0.13.18 ...
          remote:        [info] Resolving org.scala-lang#scala-compiler;2.10.7 ...
          remote:        [info] Resolving org.scala-lang#scala-reflect;2.10.7 ...
          remote:        [info] Resolving org.scala-sbt#interface;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#io;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#control;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#launcher-interface;1.0.1 ...
          remote:        [info] Resolving org.scala-sbt#completion;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#collections;0.13.18 ...
          remote:        [info] Resolving jline#jline;2.14.5 ...
          remote:        [info] Resolving org.scala-sbt#api;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#classfile;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#logging;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#process;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#compiler-integration;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#incremental-compiler;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#relation;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#compile;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#persist;0.13.18 ...
          remote:        [info] Resolving org.scala-tools.sbinary#sbinary_2.10;0.4.2 ...
          remote:        [info] Resolving org.scala-sbt#compiler-ivy-integration;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#ivy;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#cross;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-b18f59ea3bc914a297bb6f1a4f7fb0ace399e310 ...
          remote:        [info] Resolving com.jcraft#jsch;0.1.50 ...
          remote:        [info] Resolving org.scala-sbt#serialization_2.10;0.1.2 ...
          remote:        [info] Resolving org.scala-lang.modules#scala-pickling_2.10;0.10.1 ...
          remote:        [info] Resolving org.scalamacros#quasiquotes_2.10;2.0.1 ...
          remote:        [info] Resolving org.json4s#json4s-core_2.10;3.2.10 ...
          remote:        [info] Resolving org.json4s#json4s-ast_2.10;3.2.10 ...
          remote:        [info] Resolving com.thoughtworks.paranamer#paranamer;2.6 ...
          remote:        [info] Resolving org.spire-math#jawn-parser_2.10;0.6.0 ...
          remote:        [info] Resolving org.spire-math#json4s-support_2.10;0.6.0 ...
          remote:        [info] Resolving org.scala-sbt#run;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#task-system;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#tasks;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#tracking;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#cache;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#testing;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#test-agent;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#test-interface;1.0 ...
          remote:        [info] Resolving org.scala-sbt#main-settings;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#apply-macro;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#command;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#template-resolver;0.1 ...
          remote:        [info] Resolving org.scala-sbt#logic;0.13.18 ...
          remote:        [info] Resolving org.scala-sbt#compiler-interface;0.13.18 ...
          remote:        [info] Resolving org.scala-lang#jline;2.10.7 ...
          remote:        [info] Resolving org.fusesource.jansi#jansi;1.4 ...
          remote:        [info] Done updating.
          remote:        [warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
          remote:        [warn]
          remote:        [warn] 	* org.codehaus.plexus:plexus-utils:3.0.17 is selected over {2.1, 1.5.5}
          remote:        [warn] 	    +- org.apache.maven:maven-settings:3.2.2              (depends on 3.0.17)
          remote:        [warn] 	    +- org.apache.maven:maven-repository-metadata:3.2.2   (depends on 3.0.17)
          remote:        [warn] 	    +- org.apache.maven:maven-aether-provider:3.2.2       (depends on 3.0.17)
          remote:        [warn] 	    +- org.apache.maven:maven-model:3.2.2                 (depends on 3.0.17)
          remote:        [warn] 	    +- org.apache.maven:maven-core:3.2.2                  (depends on 3.0.17)
          remote:        [warn] 	    +- org.apache.maven:maven-artifact:3.2.2              (depends on 3.0.17)
          remote:        [warn] 	    +- org.apache.maven:maven-settings-builder:3.2.2      (depends on 3.0.17)
          remote:        [warn] 	    +- org.apache.maven:maven-model-builder:3.2.2         (depends on 3.0.17)
          remote:        [warn] 	    +- org.sonatype.plexus:plexus-sec-dispatcher:1.3      (depends on 1.5.5)
          remote:        [warn] 	    +- org.eclipse.sisu:org.eclipse.sisu.plexus:0.0.0.M5  (depends on 2.1)
          remote:        [warn]
          remote:        [warn] Run 'evicted' to see detailed eviction warnings
          remote:        [info] Set current project to sbt-0.13.18-minimal-with-native-packager (in build file:$BUILD_DIR/)
          remote:        [info] Updating {file:$BUILD_DIR/}$BUILD_ID...
          remote:        [info] Resolving org.scala-lang#scala-library;2.13.17 ...
          remote:        [info] Resolving dev.zio#zio-http_2.13;3.5.1 ...
          remote:        [info] Resolving org.scala-lang#scala-reflect;2.13.17 ...
          remote:        [info] Resolving dev.zio#zio_2.13;2.1.21 ...
          remote:        [info] Resolving dev.zio#zio-internal-macros_2.13;2.1.21 ...
          remote:        [info] Resolving dev.zio#zio-stacktracer_2.13;2.1.21 ...
          remote:        [info] Resolving dev.zio#izumi-reflect_2.13;3.0.6 ...
          remote:        [info] Resolving dev.zio#izumi-reflect-thirdparty-boopickle-shaded_2.13;3.0.6 ...
          remote:        [info] Resolving org.scala-lang.modules#scala-collection-compat_2.13;2.13.0 ...
          remote:        [info] Resolving dev.zio#zio-streams_2.13;2.1.21 ...
          remote:        [info] Resolving dev.zio#zio-schema_2.13;1.7.4 ...
          remote:        [info] Resolving dev.zio#zio-schema-macros_2.13;1.7.4 ...
          remote:        [info] Resolving dev.zio#zio-prelude_2.13;1.0.0-RC41 ...
          remote:        [info] Resolving dev.zio#zio-prelude-macros_2.13;1.0.0-RC41 ...
          remote:        [info] Resolving dev.zio#zio-constraintless_2.13;0.3.3 ...
          remote:        [info] Resolving dev.zio#zio-schema-json_2.13;1.7.4 ...
          remote:        [info] Resolving dev.zio#zio-schema-derivation_2.13;1.7.4 ...
          remote:        [info] Resolving dev.zio#zio-json_2.13;0.7.44 ...
          remote:        [info] Resolving com.softwaremill.magnolia1_2#magnolia_2.13;1.1.10 ...
          remote:        [info] Resolving dev.zio#zio-schema-protobuf_2.13;1.7.4 ...
          remote:        [info] Resolving io.netty#netty-codec-http;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-common;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-buffer;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-transport;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-resolver;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-codec-base;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-codec-compression;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-handler;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-transport-native-unix-common;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-handler-proxy;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-codec-socks;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-transport-native-epoll;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-transport-classes-epoll;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-transport-native-kqueue;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-transport-classes-kqueue;4.2.6.Final ...
          remote:        [info] Resolving io.netty#netty-pkitesting;4.2.6.Final ...
          remote:        [info] Resolving org.bouncycastle#bcpkix-jdk18on;1.80 ...
          remote:        [info] Resolving org.bouncycastle#bcutil-jdk18on;[1.80,1.81) ...
          remote:        [info] Resolving org.bouncycastle#bcutil-jdk18on;[1.80,1.81) ...
          remote:        [info] Resolving org.bouncycastle#bcprov-jdk18on;1.80 ...
          remote:        [info] Resolving org.scala-lang#scala-compiler;2.13.17 ...
          remote:        [info] Resolving io.github.java-diff-utils#java-diff-utils;4.16 ...
          remote:        [info] Resolving org.jline#jline;3.29.0 ...
          remote:        [info] Done updating.
          remote:        [warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
          remote:        [warn]
          remote:        [warn] 	* org.bouncycastle:bcprov-jdk18on:1.80 is selected over [1.80,1.81)
          remote:        [warn] 	    +- org.bouncycastle:bcutil-jdk18on:1.80               (depends on [1.80,1.81))
          remote:        [warn] 	    +- io.netty:netty-pkitesting:4.2.6.Final              (depends on [1.80,1.81))
          remote:        [warn]
          remote:        [warn] Run 'evicted' to see detailed eviction warnings
          remote:        [info] Compiling 1 Scala source to $BUILD_DIR/target/scala-2.13/classes...
          remote:        [success] Total time: $DURATION, completed $DATETIME
          remote:        [info] Wrote $BUILD_DIR/target/scala-2.13/sbt-0-13-18-minimal-with-native-packager_2.13-0.1-SNAPSHOT.pom
          remote:        [info] Packaging $BUILD_DIR/target/scala-2.13/sbt-0-13-18-minimal-with-native-packager_2.13-0.1-SNAPSHOT.jar ...
          remote:        [info] Done packaging.
          remote:        [success] Total time: $DURATION, completed $DATETIME
          remote: -----> Collecting sbt plugin information
          remote: -----> Collecting dependency information
          remote: -----> Copying sbt and dependencies into slug for runtime use
          remote: -----> Dropping compilation artifacts from the slug
          remote: -----> Discovering process types
          remote:        Procfile declares types     -> (none)
          remote:        Default types for buildpack -> web

          remote: -----> Compressing...
          remote:        Done: 99.8M
        OUTPUT
      end
    end
  end
end
