# frozen_string_literal: true

require_relative 'spec_helper'

describe 'Scala buildpack' do
  it 'makes sbt 1.x available at runtime' do
    new_default_hatchet_runner('sbt-1.11.7-minimal-with-native-packager').tap do |app|
      app.deploy do
        sbt_about_output = app.run('sbt about').gsub(/\w+ \d+, \d+ \d+:\d+:\d+ [AP]M/, '$TIMESTAMP')

        expect(sbt_about_output).to eq(<<~OUTPUT)
          [info] [launcher] getting org.scala-sbt sbt 1.11.7  (this may take some time)...
          [info] [launcher] getting Scala 2.12.20 (for sbt)...
          $TIMESTAMP org.jline.utils.Log logr
          WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
          [info] welcome to sbt 1.11.7 (Azul Systems, Inc. Java 21.0.9)
          [info] loading global plugins from /app/.sbt_home/plugins
          [info] compiling 1 Scala source to /app/.sbt_home/plugins/target/scala-2.12/sbt-1.0/classes ...
          [info] done compiling
          [info] loading settings for project app-build from plugins.sbt...
          [info] loading project definition from /app/project
          [info] loading settings for project app from build.sbt...
          [info] set current project to sbt-1.11.7-minimal-with-native-packager (in build file:/app/)
          [info] This is sbt 1.11.7
          [info] The current project is ProjectRef(uri("file:/app/"), "app") 0.1.0-SNAPSHOT
          [info] The current project is built against Scala 2.13.17
          [info] Available Plugins
          [info]  - HerokuBuildpackPlugin
          [info]  - com.typesafe.sbt.SbtNativePackager
          [info]  - com.typesafe.sbt.packager.archetypes.JavaAppPackaging
          [info]  - com.typesafe.sbt.packager.archetypes.JavaServerAppPackaging
          [info]  - com.typesafe.sbt.packager.archetypes.jar.ClasspathJarPlugin
          [info]  - com.typesafe.sbt.packager.archetypes.jar.LauncherJarPlugin
          [info]  - com.typesafe.sbt.packager.archetypes.jlink.JlinkPlugin
          [info]  - com.typesafe.sbt.packager.archetypes.scripts.AshScriptPlugin
          [info]  - com.typesafe.sbt.packager.archetypes.scripts.BashStartScriptPlugin
          [info]  - com.typesafe.sbt.packager.archetypes.scripts.BatStartScriptPlugin
          [info]  - com.typesafe.sbt.packager.archetypes.systemloader.SystemVPlugin
          [info]  - com.typesafe.sbt.packager.archetypes.systemloader.SystemdPlugin
          [info]  - com.typesafe.sbt.packager.archetypes.systemloader.SystemloaderPlugin
          [info]  - com.typesafe.sbt.packager.archetypes.systemloader.UpstartPlugin
          [info]  - com.typesafe.sbt.packager.debian.DebianDeployPlugin
          [info]  - com.typesafe.sbt.packager.debian.DebianPlugin
          [info]  - com.typesafe.sbt.packager.debian.JDebPackaging
          [info]  - com.typesafe.sbt.packager.docker.DockerPlugin
          [info]  - com.typesafe.sbt.packager.docker.DockerSpotifyClientPlugin
          [info]  - com.typesafe.sbt.packager.graalvmnativeimage.GraalVMNativeImagePlugin
          [info]  - com.typesafe.sbt.packager.jdkpackager.JDKPackagerDeployPlugin
          [info]  - com.typesafe.sbt.packager.jdkpackager.JDKPackagerPlugin
          [info]  - com.typesafe.sbt.packager.linux.LinuxPlugin
          [info]  - com.typesafe.sbt.packager.rpm.RpmDeployPlugin
          [info]  - com.typesafe.sbt.packager.rpm.RpmPlugin
          [info]  - com.typesafe.sbt.packager.universal.UniversalDeployPlugin
          [info]  - com.typesafe.sbt.packager.universal.UniversalPlugin
          [info]  - com.typesafe.sbt.packager.windows.WindowsDeployPlugin
          [info]  - com.typesafe.sbt.packager.windows.WindowsPlugin
          [info]  - sbt.ScriptedPlugin
          [info]  - sbt.plugins.CorePlugin
          [info]  - sbt.plugins.Giter8TemplatePlugin
          [info]  - sbt.plugins.IvyPlugin
          [info]  - sbt.plugins.JUnitXmlReportPlugin
          [info]  - sbt.plugins.JvmPlugin
          [info]  - sbt.plugins.MiniDependencyTreePlugin
          [info]  - sbt.plugins.SbtPlugin
          [info]  - sbt.plugins.SemanticdbPlugin
          [info] sbt, sbt plugins, and build definitions are using Scala 2.12.20
        OUTPUT
      end
    end
  end

  it 'makes sbt 1.x available at runtime without native packager' do
    new_default_hatchet_runner('sbt-1.11.7-minimal-no-native-packager').tap do |app|
      app.deploy do
        sbt_about_output = app.run('sbt about')
                              .gsub(/\w+ \d+, \d+ \d+:\d+:\d+ [AP]M/, '$TIMESTAMP')
                              .gsub(/\[warn\] In the last .+ were spent in GC\..+\n/, '')

        expect(sbt_about_output).to eq(<<~OUTPUT)
          $TIMESTAMP org.jline.utils.Log logr
          WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
          [info] welcome to sbt 1.11.7 (Azul Systems, Inc. Java 21.0.9)
          [info] loading global plugins from /app/.sbt_home/plugins
          [info] compiling 1 Scala source to /app/.sbt_home/plugins/target/scala-2.12/sbt-1.0/classes ...
          [info] done compiling
          [info] loading project definition from /app/project
          [info] loading settings for project app from build.sbt...
          [info] set current project to sbt-1.11.7-minimal-no-native-packager (in build file:/app/)
          [info] This is sbt 1.11.7
          [info] The current project is ProjectRef(uri("file:/app/"), "app") 0.1.0-SNAPSHOT
          [info] The current project is built against Scala 2.13.17
          [info] Available Plugins
          [info]  - HerokuBuildpackPlugin
          [info]  - sbt.ScriptedPlugin
          [info]  - sbt.plugins.CorePlugin
          [info]  - sbt.plugins.Giter8TemplatePlugin
          [info]  - sbt.plugins.IvyPlugin
          [info]  - sbt.plugins.JUnitXmlReportPlugin
          [info]  - sbt.plugins.JvmPlugin
          [info]  - sbt.plugins.MiniDependencyTreePlugin
          [info]  - sbt.plugins.SbtPlugin
          [info]  - sbt.plugins.SemanticdbPlugin
          [info] sbt, sbt plugins, and build definitions are using Scala 2.12.20
        OUTPUT
      end
    end
  end

  it 'makes sbt 0.x available at runtime' do
    new_default_hatchet_runner('sbt-0.13.18-minimal-with-native-packager').tap do |app|
      app.before_deploy do
        # Override sbt-extra's default for OpenJDK >9 and <17 to use JVMCI. Enabling JVMCI causes non-fatal
        # compile errors that bloat the build log. These compile errors are also non-deterministic so checking
        # against the output will not work reliably. We will eventually remove sbt-extras in PR #291 that will
        # make this configuration unnecessary.
        #
        # See: https://github.com/dwijnand/sbt-extras/issues/344
        app.set_config('JVM_OPTS' => '-XX:+UnlockExperimentalVMOptions -XX:-UseJVMCICompiler')
      end

      app.deploy do
        sbt_about_output = app.run('sbt about')
                              .gsub(/\(\d+ms\)/, '($DURATION)')
                              .gsub(%r{\((\d+kB)/\d+ms\)}, '(\1/$DURATION)')
                              .gsub(/\d+\.\d+ s/, '$DURATION s')
                              .gsub(/\[(info|warn|error|success|debug)\] $/, '[\1]')

        expect(sbt_about_output).to eq(<<~OUTPUT)
          Getting org.scala-sbt sbt 0.13.18  (this may take some time)...
          WARNING: An illegal reflective access operation has occurred
          WARNING: Illegal reflective access by org.apache.ivy.util.url.IvyAuthenticator (file:/app/.heroku/scala/sbt-launcher/sbt-launch-0.13.18.jar) to field java.net.Authenticator.theAuthenticator
          WARNING: Please consider reporting this to the maintainers of org.apache.ivy.util.url.IvyAuthenticator
          WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
          WARNING: All illegal access operations will be denied in a future release
          downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.18/jars/sbt.jar ...
          	[SUCCESSFUL ] org.scala-sbt#sbt;0.13.18!sbt.jar ($DURATION)
          downloading https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.10.7/scala-library-2.10.7.jar ...
          	[SUCCESSFUL ] org.scala-lang#scala-library;2.10.7!scala-library.jar ($DURATION)
          downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main/0.13.18/jars/main.jar ...
          	[SUCCESSFUL ] org.scala-sbt#main;0.13.18!main.jar ($DURATION)
          downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-interface/0.13.18/jars/compiler-interface.jar ...
          	[SUCCESSFUL ] org.scala-sbt#compiler-interface;0.13.18!compiler-interface.jar ($DURATION)
          downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/actions/0.13.18/jars/actions.jar ...
          	[SUCCESSFUL ] org.scala-sbt#actions;0.13.18!actions.jar ($DURATION)
          downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main-settings/0.13.18/jars/main-settings.jar ...
          	[SUCCESSFUL ] org.scala-sbt#main-settings;0.13.18!main-settings.jar ($DURATION)
          downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/interface/0.13.18/jars/interface.jar ...
          	[SUCCESSFUL ] org.scala-sbt#interface;0.13.18!interface.jar ($DURATION)
          downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/io/0.13.18/jars/io.jar ...
          	[SUCCESSFUL ] org.scala-sbt#io;0.13.18!io.jar ($DURATION)
          downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/ivy/0.13.18/jars/ivy.jar ...
          	[SUCCESSFUL ] org.scala-sbt#ivy;0.13.18!ivy.jar ($DURATION)
          downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/logging/0.13.18/jars/logging.jar ...
          	[SUCCESSFUL ] org.scala-sbt#logging;0.13.18!logging.jar ($DURATION)
          downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/logic/0.13.18/jars/logic.jar ...
          	[SUCCESSFUL ] org.scala-sbt#logic;0.13.18!logic.jar ($DURATION)
          downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/process/0.13.18/jars/process.jar ...
          	[SUCCESSFUL ] org.scala-sbt#process;0.13.18!process.jar ($DURATION)
          downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/run/0.13.18/jars/run.jar ...
          	[SUCCESSFUL ] org.scala-sbt#run;0.13.18!run.jar ($DURATION)
          downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/command/0.13.18/jars/command.jar ...
          	[SUCCESSFUL ] org.scala-sbt#command;0.13.18!command.jar ($DURATION)
          downloading https://repo1.maven.org/maven2/org/scala-sbt/launcher-interface/1.0.1/launcher-interface-1.0.1.jar ...
          	[SUCCESSFUL ] org.scala-sbt#launcher-interface;1.0.1!launcher-interface.jar ($DURATION)
          downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/classpath/0.13.18/jars/classpath.jar ...
          	[SUCCESSFUL ] org.scala-sbt#classpath;0.13.18!classpath.jar ($DURATION)
          downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/completion/0.13.18/jars/completion.jar ...
          	[SUCCESSFUL ] org.scala-sbt#completion;0.13.18!completion.jar ($DURATION)
          downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/api/0.13.18/jars/api.jar ...
          	[SUCCESSFUL ] org.scala-sbt#api;0.13.18!api.jar ($DURATION)
          downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-integration/0.13.18/jars/compiler-integration.jar ...
          	[SUCCESSFUL ] org.scala-sbt#compiler-integration;0.13.18!compiler-integration.jar ($DURATION)
          downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-ivy-integration/0.13.18/jars/compiler-ivy-integration.jar ...
          	[SUCCESSFUL ] org.scala-sbt#compiler-ivy-integration;0.13.18!compiler-ivy-integration.jar ($DURATION)
          downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/relation/0.13.18/jars/relation.jar ...
          	[SUCCESSFUL ] org.scala-sbt#relation;0.13.18!relation.jar ($DURATION)
          downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/task-system/0.13.18/jars/task-system.jar ...
          	[SUCCESSFUL ] org.scala-sbt#task-system;0.13.18!task-system.jar ($DURATION)
          downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/tasks/0.13.18/jars/tasks.jar ...
          	[SUCCESSFUL ] org.scala-sbt#tasks;0.13.18!tasks.jar ($DURATION)
          downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/tracking/0.13.18/jars/tracking.jar ...
          	[SUCCESSFUL ] org.scala-sbt#tracking;0.13.18!tracking.jar ($DURATION)
          downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/testing/0.13.18/jars/testing.jar ...
          	[SUCCESSFUL ] org.scala-sbt#testing;0.13.18!testing.jar ($DURATION)
          downloading https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.10.7/scala-compiler-2.10.7.jar ...
          	[SUCCESSFUL ] org.scala-lang#scala-compiler;2.10.7!scala-compiler.jar ($DURATION)
          downloading https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.10.7/scala-reflect-2.10.7.jar ...
          	[SUCCESSFUL ] org.scala-lang#scala-reflect;2.10.7!scala-reflect.jar ($DURATION)
          downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/control/0.13.18/jars/control.jar ...
          	[SUCCESSFUL ] org.scala-sbt#control;0.13.18!control.jar ($DURATION)
          downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/collections/0.13.18/jars/collections.jar ...
          	[SUCCESSFUL ] org.scala-sbt#collections;0.13.18!collections.jar ($DURATION)
          downloading https://repo1.maven.org/maven2/jline/jline/2.14.5/jline-2.14.5.jar ...
          	[SUCCESSFUL ] jline#jline;2.14.5!jline.jar ($DURATION)
          downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/classfile/0.13.18/jars/classfile.jar ...
          	[SUCCESSFUL ] org.scala-sbt#classfile;0.13.18!classfile.jar ($DURATION)
          downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/incremental-compiler/0.13.18/jars/incremental-compiler.jar ...
          	[SUCCESSFUL ] org.scala-sbt#incremental-compiler;0.13.18!incremental-compiler.jar ($DURATION)
          downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compile/0.13.18/jars/compile.jar ...
          	[SUCCESSFUL ] org.scala-sbt#compile;0.13.18!compile.jar ($DURATION)
          downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/persist/0.13.18/jars/persist.jar ...
          	[SUCCESSFUL ] org.scala-sbt#persist;0.13.18!persist.jar ($DURATION)
          downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-tools.sbinary/sbinary_2.10/0.4.2/jars/sbinary_2.10.jar ...
          	[SUCCESSFUL ] org.scala-tools.sbinary#sbinary_2.10;0.4.2!sbinary_2.10.jar ($DURATION)
          downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/cross/0.13.18/jars/cross.jar ...
          	[SUCCESSFUL ] org.scala-sbt#cross;0.13.18!cross.jar ($DURATION)
          downloading https://repo1.maven.org/maven2/org/scala-sbt/ivy/ivy/2.3.0-sbt-b18f59ea3bc914a297bb6f1a4f7fb0ace399e310/ivy-2.3.0-sbt-b18f59ea3bc914a297bb6f1a4f7fb0ace399e310.jar ...
          	[SUCCESSFUL ] org.scala-sbt.ivy#ivy;2.3.0-sbt-b18f59ea3bc914a297bb6f1a4f7fb0ace399e310!ivy.jar ($DURATION)
          downloading https://repo1.maven.org/maven2/com/jcraft/jsch/0.1.50/jsch-0.1.50.jar ...
          	[SUCCESSFUL ] com.jcraft#jsch;0.1.50!jsch.jar ($DURATION)
          downloading https://repo1.maven.org/maven2/org/scala-sbt/serialization_2.10/0.1.2/serialization_2.10-0.1.2.jar ...
          	[SUCCESSFUL ] org.scala-sbt#serialization_2.10;0.1.2!serialization_2.10.jar ($DURATION)
          downloading https://repo1.maven.org/maven2/org/scala-lang/modules/scala-pickling_2.10/0.10.1/scala-pickling_2.10-0.10.1.jar ...
          	[SUCCESSFUL ] org.scala-lang.modules#scala-pickling_2.10;0.10.1!scala-pickling_2.10.jar ($DURATION)
          downloading https://repo1.maven.org/maven2/org/json4s/json4s-core_2.10/3.2.10/json4s-core_2.10-3.2.10.jar ...
          	[SUCCESSFUL ] org.json4s#json4s-core_2.10;3.2.10!json4s-core_2.10.jar ($DURATION)
          downloading https://repo1.maven.org/maven2/org/spire-math/jawn-parser_2.10/0.6.0/jawn-parser_2.10-0.6.0.jar ...
          	[SUCCESSFUL ] org.spire-math#jawn-parser_2.10;0.6.0!jawn-parser_2.10.jar ($DURATION)
          downloading https://repo1.maven.org/maven2/org/spire-math/json4s-support_2.10/0.6.0/json4s-support_2.10-0.6.0.jar ...
          	[SUCCESSFUL ] org.spire-math#json4s-support_2.10;0.6.0!json4s-support_2.10.jar ($DURATION)
          downloading https://repo1.maven.org/maven2/org/scalamacros/quasiquotes_2.10/2.0.1/quasiquotes_2.10-2.0.1.jar ...
          	[SUCCESSFUL ] org.scalamacros#quasiquotes_2.10;2.0.1!quasiquotes_2.10.jar ($DURATION)
          downloading https://repo1.maven.org/maven2/org/json4s/json4s-ast_2.10/3.2.10/json4s-ast_2.10-3.2.10.jar ...
          	[SUCCESSFUL ] org.json4s#json4s-ast_2.10;3.2.10!json4s-ast_2.10.jar ($DURATION)
          downloading https://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.6/paranamer-2.6.jar ...
          	[SUCCESSFUL ] com.thoughtworks.paranamer#paranamer;2.6!paranamer.jar ($DURATION)
          downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/cache/0.13.18/jars/cache.jar ...
          	[SUCCESSFUL ] org.scala-sbt#cache;0.13.18!cache.jar ($DURATION)
          downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/test-agent/0.13.18/jars/test-agent.jar ...
          	[SUCCESSFUL ] org.scala-sbt#test-agent;0.13.18!test-agent.jar ($DURATION)
          downloading https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar ...
          	[SUCCESSFUL ] org.scala-sbt#test-interface;1.0!test-interface.jar ($DURATION)
          downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/apply-macro/0.13.18/jars/apply-macro.jar ...
          	[SUCCESSFUL ] org.scala-sbt#apply-macro;0.13.18!apply-macro.jar ($DURATION)
          downloading https://repo1.maven.org/maven2/org/scala-sbt/template-resolver/0.1/template-resolver-0.1.jar ...
          	[SUCCESSFUL ] org.scala-sbt#template-resolver;0.1!template-resolver.jar ($DURATION)
          :: retrieving :: org.scala-sbt#boot-app
          	confs: [default]
          	49 artifacts copied, 0 already retrieved (17584kB/$DURATION)
          Getting Scala 2.10.7 (for sbt)...
          downloading https://repo1.maven.org/maven2/org/scala-lang/jline/2.10.7/jline-2.10.7.jar ...
          	[SUCCESSFUL ] org.scala-lang#jline;2.10.7!jline.jar ($DURATION)
          downloading https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/1.4/jansi-1.4.jar ...
          	[SUCCESSFUL ] org.fusesource.jansi#jansi;1.4!jansi.jar ($DURATION)
          :: retrieving :: org.scala-sbt#boot-scala
          	confs: [default]
          	5 artifacts copied, 0 already retrieved (24560kB/$DURATION)
          [info] Loading global plugins from /app/.sbt_home/plugins
          [info] Updating {file:/app/.sbt_home/plugins/}global-plugins...
          [info] Resolving org.scala-lang#scala-library;2.10.7 ...
          [info] Resolving org.scala-sbt#sbt;0.13.18 ...
          [info] Resolving org.scala-sbt#main;0.13.18 ...
          [info] Resolving org.scala-sbt#actions;0.13.18 ...
          [info] Resolving org.scala-sbt#classpath;0.13.18 ...
          [info] Resolving org.scala-lang#scala-compiler;2.10.7 ...
          [info] Resolving org.scala-lang#scala-reflect;2.10.7 ...
          [info] Resolving org.scala-sbt#interface;0.13.18 ...
          [info] Resolving org.scala-sbt#io;0.13.18 ...
          [info] Resolving org.scala-sbt#control;0.13.18 ...
          [info] Resolving org.scala-sbt#launcher-interface;1.0.1 ...
          [info] Resolving org.scala-sbt#completion;0.13.18 ...
          [info] Resolving org.scala-sbt#collections;0.13.18 ...
          [info] Resolving jline#jline;2.14.5 ...
          [info] Resolving org.scala-sbt#api;0.13.18 ...
          [info] Resolving org.scala-sbt#classfile;0.13.18 ...
          [info] Resolving org.scala-sbt#logging;0.13.18 ...
          [info] Resolving org.scala-sbt#process;0.13.18 ...
          [info] Resolving org.scala-sbt#compiler-integration;0.13.18 ...
          [info] Resolving org.scala-sbt#incremental-compiler;0.13.18 ...
          [info] Resolving org.scala-sbt#relation;0.13.18 ...
          [info] Resolving org.scala-sbt#compile;0.13.18 ...
          [info] Resolving org.scala-sbt#persist;0.13.18 ...
          [info] Resolving org.scala-tools.sbinary#sbinary_2.10;0.4.2 ...
          [info] Resolving org.scala-sbt#compiler-ivy-integration;0.13.18 ...
          [info] Resolving org.scala-sbt#ivy;0.13.18 ...
          [info] Resolving org.scala-sbt#cross;0.13.18 ...
          [info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-b18f59ea3bc914a297bb6f1a4f7fb0ace399e310 ...
          [info] Resolving com.jcraft#jsch;0.1.50 ...
          [info] Resolving org.scala-sbt#serialization_2.10;0.1.2 ...
          [info] Resolving org.scala-lang.modules#scala-pickling_2.10;0.10.1 ...
          [info] Resolving org.scalamacros#quasiquotes_2.10;2.0.1 ...
          [info] Resolving org.json4s#json4s-core_2.10;3.2.10 ...
          [info] Resolving org.json4s#json4s-ast_2.10;3.2.10 ...
          [info] Resolving com.thoughtworks.paranamer#paranamer;2.6 ...
          [info] Resolving org.spire-math#jawn-parser_2.10;0.6.0 ...
          [info] Resolving org.spire-math#json4s-support_2.10;0.6.0 ...
          [info] Resolving org.scala-sbt#run;0.13.18 ...
          [info] Resolving org.scala-sbt#task-system;0.13.18 ...
          [info] Resolving org.scala-sbt#tasks;0.13.18 ...
          [info] Resolving org.scala-sbt#tracking;0.13.18 ...
          [info] Resolving org.scala-sbt#cache;0.13.18 ...
          [info] Resolving org.scala-sbt#testing;0.13.18 ...
          [info] Resolving org.scala-sbt#test-agent;0.13.18 ...
          [info] Resolving org.scala-sbt#test-interface;1.0 ...
          [info] Resolving org.scala-sbt#main-settings;0.13.18 ...
          [info] Resolving org.scala-sbt#apply-macro;0.13.18 ...
          [info] Resolving org.scala-sbt#command;0.13.18 ...
          [info] Resolving org.scala-sbt#template-resolver;0.1 ...
          [info] Resolving org.scala-sbt#logic;0.13.18 ...
          [info] Resolving org.scala-sbt#compiler-interface;0.13.18 ...
          [info] Resolving org.scala-lang#jline;2.10.7 ...
          [info] Resolving org.fusesource.jansi#jansi;1.4 ...
          [info] Done updating.
          [info] Compiling 1 Scala source to /app/.sbt_home/plugins/target/scala-2.10/sbt-0.13/classes...
          [info] 'compiler-interface' not yet compiled for Scala 2.10.7. Compiling...
          [info]   Compilation completed in $DURATION s
          [info] Loading project definition from /app/project
          [info] Updating {file:/app/project/}app-build...
          [info] Resolving org.scala-sbt#global-plugins;0.0 ...
          [info] Resolving com.typesafe.sbt#sbt-native-packager;0.7.5-RC2 ...
          [info] Resolving com.typesafe.sbt#sbt-native-packager;0.7.5-RC2 ...
          [info] Resolving org.apache.commons#commons-compress;1.4.1 ...
          [info] Resolving org.apache.commons#commons-compress;1.4.1 ...
          [info] Resolving org.apache.commons#commons-parent;24 ...
          [info] Resolving org.apache.commons#commons-parent;24 ...
          [info] Resolving org.apache#apache;9 ...
          [info] Resolving org.apache#apache;9 ...
          [info] Resolving org.tukaani#xz;1.0 ...
          [info] Resolving org.tukaani#xz;1.0 ...
          [info] Resolving org.vafer#jdeb;1.3 ...
          [info] Resolving org.vafer#jdeb;1.3 ...
          [info] Resolving commons-io#commons-io;2.4 ...
          [info] Resolving commons-io#commons-io;2.4 ...
          [info] Resolving org.apache.commons#commons-parent;25 ...
          [info] Resolving org.apache.commons#commons-parent;25 ...
          [info] Resolving org.apache#apache;9 ...
          [info] Resolving org.apache.commons#commons-compress;1.7 ...
          [info] Resolving org.apache.commons#commons-compress;1.7 ...
          [info] Resolving org.apache.commons#commons-parent;32 ...
          [info] Resolving org.apache.commons#commons-parent;32 ...
          [info] Resolving org.apache#apache;13 ...
          [info] Resolving org.apache#apache;13 ...
          [info] Resolving org.tukaani#xz;1.4 ...
          [info] Resolving org.tukaani#xz;1.4 ...
          [info] Resolving org.apache.maven#maven-core;3.2.2 ...
          [info] Resolving org.apache.maven#maven-core;3.2.2 ...
          [info] Resolving org.apache.maven#maven;3.2.2 ...
          [info] Resolving org.apache.maven#maven;3.2.2 ...
          [info] Resolving org.apache.maven#maven-parent;24 ...
          [info] Resolving org.apache.maven#maven-parent;24 ...
          [info] Resolving org.apache#apache;14 ...
          [info] Resolving org.apache#apache;14 ...
          [info] Resolving org.apache.maven#maven-model;3.2.2 ...
          [info] Resolving org.apache.maven#maven-model;3.2.2 ...
          [info] Resolving org.apache.maven#maven;3.2.2 ...
          [info] Resolving org.codehaus.plexus#plexus-utils;3.0.17 ...
          [info] Resolving org.codehaus.plexus#plexus-utils;3.0.17 ...
          [info] Resolving org.codehaus.plexus#plexus;3.3.1 ...
          [info] Resolving org.codehaus.plexus#plexus;3.3.1 ...
          [info] Resolving org.sonatype.spice#spice-parent;17 ...
          [info] Resolving org.sonatype.spice#spice-parent;17 ...
          [info] Resolving org.sonatype.forge#forge-parent;10 ...
          [info] Resolving org.sonatype.forge#forge-parent;10 ...
          [info] Resolving org.apache.maven#maven-settings;3.2.2 ...
          [info] Resolving org.apache.maven#maven-settings;3.2.2 ...
          [info] Resolving org.apache.maven#maven;3.2.2 ...
          [info] Resolving org.apache.maven#maven-settings-builder;3.2.2 ...
          [info] Resolving org.apache.maven#maven-settings-builder;3.2.2 ...
          [info] Resolving org.apache.maven#maven;3.2.2 ...
          [info] Resolving org.codehaus.plexus#plexus-interpolation;1.19 ...
          [info] Resolving org.codehaus.plexus#plexus-interpolation;1.19 ...
          [info] Resolving org.codehaus.plexus#plexus-components;1.3.1 ...
          [info] Resolving org.codehaus.plexus#plexus-components;1.3.1 ...
          [info] Resolving org.codehaus.plexus#plexus;3.3.1 ...
          [info] Resolving org.codehaus.plexus#plexus-component-annotations;1.5.5 ...
          [info] Resolving org.codehaus.plexus#plexus-component-annotations;1.5.5 ...
          [info] Resolving org.codehaus.plexus#plexus-containers;1.5.5 ...
          [info] Resolving org.codehaus.plexus#plexus-containers;1.5.5 ...
          [info] Resolving org.codehaus.plexus#plexus;2.0.7 ...
          [info] Resolving org.codehaus.plexus#plexus;2.0.7 ...
          [info] Resolving org.sonatype.plexus#plexus-sec-dispatcher;1.3 ...
          [info] Resolving org.sonatype.plexus#plexus-sec-dispatcher;1.3 ...
          [info] Resolving org.sonatype.spice#spice-parent;12 ...
          [info] Resolving org.sonatype.spice#spice-parent;12 ...
          [info] Resolving org.sonatype.forge#forge-parent;4 ...
          [info] Resolving org.sonatype.forge#forge-parent;4 ...
          [info] Resolving org.sonatype.plexus#plexus-cipher;1.4 ...
          [info] Resolving org.sonatype.plexus#plexus-cipher;1.4 ...
          [info] Resolving org.sonatype.spice#spice-parent;12 ...
          [info] Resolving org.apache.maven#maven-repository-metadata;3.2.2 ...
          [info] Resolving org.apache.maven#maven-repository-metadata;3.2.2 ...
          [info] Resolving org.apache.maven#maven;3.2.2 ...
          [info] Resolving org.apache.maven#maven-artifact;3.2.2 ...
          [info] Resolving org.apache.maven#maven-artifact;3.2.2 ...
          [info] Resolving org.apache.maven#maven;3.2.2 ...
          [info] Resolving org.apache.maven#maven-plugin-api;3.2.2 ...
          [info] Resolving org.apache.maven#maven-plugin-api;3.2.2 ...
          [info] Resolving org.apache.maven#maven;3.2.2 ...
          [info] Resolving org.eclipse.sisu#org.eclipse.sisu.plexus;0.0.0.M5 ...
          [info] Resolving org.eclipse.sisu#org.eclipse.sisu.plexus;0.0.0.M5 ...
          [info] Resolving org.eclipse.sisu#sisu-plexus;0.0.0.M5 ...
          [info] Resolving org.eclipse.sisu#sisu-plexus;0.0.0.M5 ...
          [info] Resolving org.sonatype.oss#oss-parent;7 ...
          [info] Resolving org.sonatype.oss#oss-parent;7 ...
          [info] Resolving javax.enterprise#cdi-api;1.0 ...
          [info] Resolving javax.enterprise#cdi-api;1.0 ...
          [info] Resolving org.jboss.weld#weld-api-parent;1.0 ...
          [info] Resolving org.jboss.weld#weld-api-parent;1.0 ...
          [info] Resolving org.jboss.weld#weld-api-bom;1.0 ...
          [info] Resolving org.jboss.weld#weld-api-bom;1.0 ...
          [info] Resolving org.jboss.weld#weld-parent;6 ...
          [info] Resolving org.jboss.weld#weld-parent;6 ...
          [info] Resolving javax.annotation#jsr250-api;1.0 ...
          [info] Resolving javax.annotation#jsr250-api;1.0 ...
          [info] Resolving javax.inject#javax.inject;1 ...
          [info] Resolving javax.inject#javax.inject;1 ...
          [info] Resolving com.google.guava#guava;10.0.1 ...
          [info] Resolving com.google.guava#guava;10.0.1 ...
          [info] Resolving com.google.guava#guava-parent;10.0.1 ...
          [info] Resolving com.google.guava#guava-parent;10.0.1 ...
          [info] Resolving org.sonatype.oss#oss-parent;7 ...
          [info] Resolving com.google.code.findbugs#jsr305;1.3.9 ...
          [info] Resolving com.google.code.findbugs#jsr305;1.3.9 ...
          [info] Resolving org.sonatype.sisu#sisu-guice;3.1.0 ...
          [info] Resolving org.sonatype.sisu#sisu-guice;3.1.0 ...
          [info] Resolving org.sonatype.sisu.inject#guice-parent;3.1.0 ...
          [info] Resolving org.sonatype.sisu.inject#guice-parent;3.1.0 ...
          [info] Resolving org.sonatype.forge#forge-parent;10 ...
          [info] Resolving aopalliance#aopalliance;1.0 ...
          [info] Resolving aopalliance#aopalliance;1.0 ...
          [info] Resolving org.eclipse.sisu#org.eclipse.sisu.inject;0.0.0.M5 ...
          [info] Resolving org.eclipse.sisu#org.eclipse.sisu.inject;0.0.0.M5 ...
          [info] Resolving org.eclipse.sisu#sisu-inject;0.0.0.M5 ...
          [info] Resolving org.eclipse.sisu#sisu-inject;0.0.0.M5 ...
          [info] Resolving org.sonatype.oss#oss-parent;7 ...
          [info] Resolving org.apache.maven#maven-model-builder;3.2.2 ...
          [info] Resolving org.apache.maven#maven-model-builder;3.2.2 ...
          [info] Resolving org.apache.maven#maven;3.2.2 ...
          [info] Resolving org.apache.maven#maven-aether-provider;3.2.2 ...
          [info] Resolving org.apache.maven#maven-aether-provider;3.2.2 ...
          [info] Resolving org.apache.maven#maven;3.2.2 ...
          [info] Resolving org.eclipse.aether#aether-api;0.9.0.M2 ...
          [info] Resolving org.eclipse.aether#aether-api;0.9.0.M2 ...
          [info] Resolving org.eclipse.aether#aether;0.9.0.M2 ...
          [info] Resolving org.eclipse.aether#aether;0.9.0.M2 ...
          [info] Resolving org.eclipse.aether#aether-spi;0.9.0.M2 ...
          [info] Resolving org.eclipse.aether#aether-spi;0.9.0.M2 ...
          [info] Resolving org.eclipse.aether#aether;0.9.0.M2 ...
          [info] Resolving org.eclipse.aether#aether-util;0.9.0.M2 ...
          [info] Resolving org.eclipse.aether#aether-util;0.9.0.M2 ...
          [info] Resolving org.eclipse.aether#aether;0.9.0.M2 ...
          [info] Resolving org.eclipse.aether#aether-impl;0.9.0.M2 ...
          [info] Resolving org.eclipse.aether#aether-impl;0.9.0.M2 ...
          [info] Resolving org.eclipse.aether#aether;0.9.0.M2 ...
          [info] Resolving org.codehaus.plexus#plexus-classworlds;2.5.1 ...
          [info] Resolving org.codehaus.plexus#plexus-classworlds;2.5.1 ...
          [info] Resolving org.codehaus.plexus#plexus;3.3.1 ...
          [info] Resolving org.apache.ant#ant;1.9.3 ...
          [info] Resolving org.apache.ant#ant;1.9.3 ...
          [info] Resolving org.apache.ant#ant-parent;1.9.3 ...
          [info] Resolving org.apache.ant#ant-parent;1.9.3 ...
          [info] Resolving org.apache.ant#ant-launcher;1.9.3 ...
          [info] Resolving org.apache.ant#ant-launcher;1.9.3 ...
          [info] Resolving org.apache.ant#ant-parent;1.9.3 ...
          [info] Resolving org.bouncycastle#bcpg-jdk15on;1.51 ...
          [info] Resolving org.bouncycastle#bcpg-jdk15on;1.51 ...
          [info] Resolving org.bouncycastle#bcprov-jdk15on;1.51 ...
          [info] Resolving org.bouncycastle#bcprov-jdk15on;1.51 ...
          [info] Resolving org.scala-lang#scala-library;2.10.7 ...
          [info] Resolving org.scala-sbt#sbt;0.13.18 ...
          [info] Resolving org.scala-sbt#main;0.13.18 ...
          [info] Resolving org.scala-sbt#actions;0.13.18 ...
          [info] Resolving org.scala-sbt#classpath;0.13.18 ...
          [info] Resolving org.scala-lang#scala-compiler;2.10.7 ...
          [info] Resolving org.scala-lang#scala-reflect;2.10.7 ...
          [info] Resolving org.scala-sbt#interface;0.13.18 ...
          [info] Resolving org.scala-sbt#io;0.13.18 ...
          [info] Resolving org.scala-sbt#control;0.13.18 ...
          [info] Resolving org.scala-sbt#launcher-interface;1.0.1 ...
          [info] Resolving org.scala-sbt#completion;0.13.18 ...
          [info] Resolving org.scala-sbt#collections;0.13.18 ...
          [info] Resolving jline#jline;2.14.5 ...
          [info] Resolving org.scala-sbt#api;0.13.18 ...
          [info] Resolving org.scala-sbt#classfile;0.13.18 ...
          [info] Resolving org.scala-sbt#logging;0.13.18 ...
          [info] Resolving org.scala-sbt#process;0.13.18 ...
          [info] Resolving org.scala-sbt#compiler-integration;0.13.18 ...
          [info] Resolving org.scala-sbt#incremental-compiler;0.13.18 ...
          [info] Resolving org.scala-sbt#relation;0.13.18 ...
          [info] Resolving org.scala-sbt#compile;0.13.18 ...
          [info] Resolving org.scala-sbt#persist;0.13.18 ...
          [info] Resolving org.scala-tools.sbinary#sbinary_2.10;0.4.2 ...
          [info] Resolving org.scala-sbt#compiler-ivy-integration;0.13.18 ...
          [info] Resolving org.scala-sbt#ivy;0.13.18 ...
          [info] Resolving org.scala-sbt#cross;0.13.18 ...
          [info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-b18f59ea3bc914a297bb6f1a4f7fb0ace399e310 ...
          [info] Resolving com.jcraft#jsch;0.1.50 ...
          [info] Resolving org.scala-sbt#serialization_2.10;0.1.2 ...
          [info] Resolving org.scala-lang.modules#scala-pickling_2.10;0.10.1 ...
          [info] Resolving org.scalamacros#quasiquotes_2.10;2.0.1 ...
          [info] Resolving org.json4s#json4s-core_2.10;3.2.10 ...
          [info] Resolving org.json4s#json4s-ast_2.10;3.2.10 ...
          [info] Resolving com.thoughtworks.paranamer#paranamer;2.6 ...
          [info] Resolving org.spire-math#jawn-parser_2.10;0.6.0 ...
          [info] Resolving org.spire-math#json4s-support_2.10;0.6.0 ...
          [info] Resolving org.scala-sbt#run;0.13.18 ...
          [info] Resolving org.scala-sbt#task-system;0.13.18 ...
          [info] Resolving org.scala-sbt#tasks;0.13.18 ...
          [info] Resolving org.scala-sbt#tracking;0.13.18 ...
          [info] Resolving org.scala-sbt#cache;0.13.18 ...
          [info] Resolving org.scala-sbt#testing;0.13.18 ...
          [info] Resolving org.scala-sbt#test-agent;0.13.18 ...
          [info] Resolving org.scala-sbt#test-interface;1.0 ...
          [info] Resolving org.scala-sbt#main-settings;0.13.18 ...
          [info] Resolving org.scala-sbt#apply-macro;0.13.18 ...
          [info] Resolving org.scala-sbt#command;0.13.18 ...
          [info] Resolving org.scala-sbt#template-resolver;0.1 ...
          [info] Resolving org.scala-sbt#logic;0.13.18 ...
          [info] Resolving org.scala-sbt#compiler-interface;0.13.18 ...
          [info] Resolving org.scala-lang#jline;2.10.7 ...
          [info] Resolving org.fusesource.jansi#jansi;1.4 ...
          [info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_2.10/sbt_0.13/0.7.5-RC2/jars/sbt-native-packager.jar ...
          [info] 	[SUCCESSFUL ] com.typesafe.sbt#sbt-native-packager;0.7.5-RC2!sbt-native-packager.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/vafer/jdeb/1.3/jdeb-1.3.jar ...
          [info] 	[SUCCESSFUL ] org.vafer#jdeb;1.3!jdeb.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/commons-io/commons-io/2.4/commons-io-2.4.jar ...
          [info] 	[SUCCESSFUL ] commons-io#commons-io;2.4!commons-io.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.7/commons-compress-1.7.jar ...
          [info] 	[SUCCESSFUL ] org.apache.commons#commons-compress;1.7!commons-compress.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/apache/maven/maven-core/3.2.2/maven-core-3.2.2.jar ...
          [info] 	[SUCCESSFUL ] org.apache.maven#maven-core;3.2.2!maven-core.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/apache/maven/maven-plugin-api/3.2.2/maven-plugin-api-3.2.2.jar ...
          [info] 	[SUCCESSFUL ] org.apache.maven#maven-plugin-api;3.2.2!maven-plugin-api.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/apache/ant/ant/1.9.3/ant-1.9.3.jar ...
          [info] 	[SUCCESSFUL ] org.apache.ant#ant;1.9.3!ant.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/bouncycastle/bcpg-jdk15on/1.51/bcpg-jdk15on-1.51.jar ...
          [info] 	[SUCCESSFUL ] org.bouncycastle#bcpg-jdk15on;1.51!bcpg-jdk15on.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/tukaani/xz/1.4/xz-1.4.jar ...
          [info] 	[SUCCESSFUL ] org.tukaani#xz;1.4!xz.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/apache/maven/maven-model/3.2.2/maven-model-3.2.2.jar ...
          [info] 	[SUCCESSFUL ] org.apache.maven#maven-model;3.2.2!maven-model.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/apache/maven/maven-settings/3.2.2/maven-settings-3.2.2.jar ...
          [info] 	[SUCCESSFUL ] org.apache.maven#maven-settings;3.2.2!maven-settings.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/apache/maven/maven-settings-builder/3.2.2/maven-settings-builder-3.2.2.jar ...
          [info] 	[SUCCESSFUL ] org.apache.maven#maven-settings-builder;3.2.2!maven-settings-builder.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/apache/maven/maven-repository-metadata/3.2.2/maven-repository-metadata-3.2.2.jar ...
          [info] 	[SUCCESSFUL ] org.apache.maven#maven-repository-metadata;3.2.2!maven-repository-metadata.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/apache/maven/maven-artifact/3.2.2/maven-artifact-3.2.2.jar ...
          [info] 	[SUCCESSFUL ] org.apache.maven#maven-artifact;3.2.2!maven-artifact.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/apache/maven/maven-model-builder/3.2.2/maven-model-builder-3.2.2.jar ...
          [info] 	[SUCCESSFUL ] org.apache.maven#maven-model-builder;3.2.2!maven-model-builder.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/apache/maven/maven-aether-provider/3.2.2/maven-aether-provider-3.2.2.jar ...
          [info] 	[SUCCESSFUL ] org.apache.maven#maven-aether-provider;3.2.2!maven-aether-provider.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/eclipse/aether/aether-impl/0.9.0.M2/aether-impl-0.9.0.M2.jar ...
          [info] 	[SUCCESSFUL ] org.eclipse.aether#aether-impl;0.9.0.M2!aether-impl.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/eclipse/aether/aether-api/0.9.0.M2/aether-api-0.9.0.M2.jar ...
          [info] 	[SUCCESSFUL ] org.eclipse.aether#aether-api;0.9.0.M2!aether-api.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/eclipse/aether/aether-util/0.9.0.M2/aether-util-0.9.0.M2.jar ...
          [info] 	[SUCCESSFUL ] org.eclipse.aether#aether-util;0.9.0.M2!aether-util.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/eclipse/sisu/org.eclipse.sisu.plexus/0.0.0.M5/org.eclipse.sisu.plexus-0.0.0.M5.jar ...
          [info] 	[SUCCESSFUL ] org.eclipse.sisu#org.eclipse.sisu.plexus;0.0.0.M5!org.eclipse.sisu.plexus.jar(eclipse-plugin) ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-interpolation/1.19/plexus-interpolation-1.19.jar ...
          [info] 	[SUCCESSFUL ] org.codehaus.plexus#plexus-interpolation;1.19!plexus-interpolation.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-utils/3.0.17/plexus-utils-3.0.17.jar ...
          [info] 	[SUCCESSFUL ] org.codehaus.plexus#plexus-utils;3.0.17!plexus-utils.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-classworlds/2.5.1/plexus-classworlds-2.5.1.jar ...
          [info] 	[SUCCESSFUL ] org.codehaus.plexus#plexus-classworlds;2.5.1!plexus-classworlds.jar(bundle) ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar ...
          [info] 	[SUCCESSFUL ] org.codehaus.plexus#plexus-component-annotations;1.5.5!plexus-component-annotations.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar ...
          [info] 	[SUCCESSFUL ] org.sonatype.plexus#plexus-sec-dispatcher;1.3!plexus-sec-dispatcher.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar ...
          [info] 	[SUCCESSFUL ] org.sonatype.plexus#plexus-cipher;1.4!plexus-cipher.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar ...
          [info] 	[SUCCESSFUL ] javax.enterprise#cdi-api;1.0!cdi-api.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/com/google/guava/guava/10.0.1/guava-10.0.1.jar ...
          [info] 	[SUCCESSFUL ] com.google.guava#guava;10.0.1!guava.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/sonatype/sisu/sisu-guice/3.1.0/sisu-guice-3.1.0-no_aop.jar ...
          [info] 	[SUCCESSFUL ] org.sonatype.sisu#sisu-guice;3.1.0!sisu-guice.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/eclipse/sisu/org.eclipse.sisu.inject/0.0.0.M5/org.eclipse.sisu.inject-0.0.0.M5.jar ...
          [info] 	[SUCCESSFUL ] org.eclipse.sisu#org.eclipse.sisu.inject;0.0.0.M5!org.eclipse.sisu.inject.jar(eclipse-plugin) ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar ...
          [info] 	[SUCCESSFUL ] javax.annotation#jsr250-api;1.0!jsr250-api.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/javax/inject/javax.inject/1/javax.inject-1.jar ...
          [info] 	[SUCCESSFUL ] javax.inject#javax.inject;1!javax.inject.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar ...
          [info] 	[SUCCESSFUL ] com.google.code.findbugs#jsr305;1.3.9!jsr305.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/aopalliance/aopalliance/1.0/aopalliance-1.0.jar ...
          [info] 	[SUCCESSFUL ] aopalliance#aopalliance;1.0!aopalliance.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/eclipse/aether/aether-spi/0.9.0.M2/aether-spi-0.9.0.M2.jar ...
          [info] 	[SUCCESSFUL ] org.eclipse.aether#aether-spi;0.9.0.M2!aether-spi.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/apache/ant/ant-launcher/1.9.3/ant-launcher-1.9.3.jar ...
          [info] 	[SUCCESSFUL ] org.apache.ant#ant-launcher;1.9.3!ant-launcher.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk15on/1.51/bcprov-jdk15on-1.51.jar ...
          [info] 	[SUCCESSFUL ] org.bouncycastle#bcprov-jdk15on;1.51!bcprov-jdk15on.jar ($DURATION)
          [info] Done updating.
          [warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
          [warn]
          [warn] 	* org.codehaus.plexus:plexus-utils:3.0.17 is selected over {2.1, 1.5.5}
          [warn] 	    +- org.apache.maven:maven-settings:3.2.2              (depends on 3.0.17)
          [warn] 	    +- org.apache.maven:maven-repository-metadata:3.2.2   (depends on 3.0.17)
          [warn] 	    +- org.apache.maven:maven-aether-provider:3.2.2       (depends on 3.0.17)
          [warn] 	    +- org.apache.maven:maven-model:3.2.2                 (depends on 3.0.17)
          [warn] 	    +- org.apache.maven:maven-core:3.2.2                  (depends on 3.0.17)
          [warn] 	    +- org.apache.maven:maven-artifact:3.2.2              (depends on 3.0.17)
          [warn] 	    +- org.apache.maven:maven-settings-builder:3.2.2      (depends on 3.0.17)
          [warn] 	    +- org.apache.maven:maven-model-builder:3.2.2         (depends on 3.0.17)
          [warn] 	    +- org.sonatype.plexus:plexus-sec-dispatcher:1.3      (depends on 1.5.5)
          [warn] 	    +- org.eclipse.sisu:org.eclipse.sisu.plexus:0.0.0.M5  (depends on 2.1)
          [warn]
          [warn] Run 'evicted' to see detailed eviction warnings
          [info] Set current project to sbt-0.13.18-minimal-with-native-packager (in build file:/app/)
          [info] Updating {file:/app/}app...
          [info] Resolving org.scala-lang#scala-library;2.13.17 ...
          [info] Resolving org.scala-lang#scala-library;2.13.17 ...
          [info] Resolving dev.zio#zio-http_2.13;3.5.1 ...
          [info] Resolving dev.zio#zio-http_2.13;3.5.1 ...
          [info] Resolving org.scala-lang#scala-reflect;2.13.17 ...
          [info] Resolving org.scala-lang#scala-reflect;2.13.17 ...
          [info] Resolving dev.zio#zio_2.13;2.1.21 ...
          [info] Resolving dev.zio#zio_2.13;2.1.21 ...
          [info] Resolving dev.zio#zio-internal-macros_2.13;2.1.21 ...
          [info] Resolving dev.zio#zio-internal-macros_2.13;2.1.21 ...
          [info] Resolving dev.zio#zio-stacktracer_2.13;2.1.21 ...
          [info] Resolving dev.zio#zio-stacktracer_2.13;2.1.21 ...
          [info] Resolving dev.zio#izumi-reflect_2.13;3.0.6 ...
          [info] Resolving dev.zio#izumi-reflect_2.13;3.0.6 ...
          [info] Resolving dev.zio#izumi-reflect-thirdparty-boopickle-shaded_2.13;3.0.6 ...
          [info] Resolving dev.zio#izumi-reflect-thirdparty-boopickle-shaded_2.13;3.0.6 ...
          [info] Resolving org.scala-lang.modules#scala-collection-compat_2.13;2.13.0 ...
          [info] Resolving org.scala-lang.modules#scala-collection-compat_2.13;2.13.0 ...
          [info] Resolving dev.zio#zio-streams_2.13;2.1.21 ...
          [info] Resolving dev.zio#zio-streams_2.13;2.1.21 ...
          [info] Resolving dev.zio#zio-schema_2.13;1.7.4 ...
          [info] Resolving dev.zio#zio-schema_2.13;1.7.4 ...
          [info] Resolving dev.zio#zio-schema-macros_2.13;1.7.4 ...
          [info] Resolving dev.zio#zio-schema-macros_2.13;1.7.4 ...
          [info] Resolving dev.zio#zio-prelude_2.13;1.0.0-RC41 ...
          [info] Resolving dev.zio#zio-prelude_2.13;1.0.0-RC41 ...
          [info] Resolving dev.zio#zio-prelude-macros_2.13;1.0.0-RC41 ...
          [info] Resolving dev.zio#zio-prelude-macros_2.13;1.0.0-RC41 ...
          [info] Resolving dev.zio#zio-constraintless_2.13;0.3.3 ...
          [info] Resolving dev.zio#zio-constraintless_2.13;0.3.3 ...
          [info] Resolving dev.zio#zio-schema-json_2.13;1.7.4 ...
          [info] Resolving dev.zio#zio-schema-json_2.13;1.7.4 ...
          [info] Resolving dev.zio#zio-schema-derivation_2.13;1.7.4 ...
          [info] Resolving dev.zio#zio-schema-derivation_2.13;1.7.4 ...
          [info] Resolving dev.zio#zio-json_2.13;0.7.44 ...
          [info] Resolving dev.zio#zio-json_2.13;0.7.44 ...
          [info] Resolving com.softwaremill.magnolia1_2#magnolia_2.13;1.1.10 ...
          [info] Resolving com.softwaremill.magnolia1_2#magnolia_2.13;1.1.10 ...
          [info] Resolving dev.zio#zio-schema-protobuf_2.13;1.7.4 ...
          [info] Resolving dev.zio#zio-schema-protobuf_2.13;1.7.4 ...
          [info] Resolving io.netty#netty-codec-http;4.2.6.Final ...
          [info] Resolving io.netty#netty-codec-http;4.2.6.Final ...
          [info] Resolving io.netty#netty-parent;4.2.6.Final ...
          [info] Resolving io.netty#netty-parent;4.2.6.Final ...
          [info] Resolving org.sonatype.oss#oss-parent;9 ...
          [info] Resolving io.netty#netty-common;4.2.6.Final ...
          [info] Resolving io.netty#netty-common;4.2.6.Final ...
          [info] Resolving io.netty#netty-parent;4.2.6.Final ...
          [info] Resolving io.netty#netty-buffer;4.2.6.Final ...
          [info] Resolving io.netty#netty-buffer;4.2.6.Final ...
          [info] Resolving io.netty#netty-parent;4.2.6.Final ...
          [info] Resolving io.netty#netty-transport;4.2.6.Final ...
          [info] Resolving io.netty#netty-transport;4.2.6.Final ...
          [info] Resolving io.netty#netty-parent;4.2.6.Final ...
          [info] Resolving io.netty#netty-resolver;4.2.6.Final ...
          [info] Resolving io.netty#netty-resolver;4.2.6.Final ...
          [info] Resolving io.netty#netty-parent;4.2.6.Final ...
          [info] Resolving io.netty#netty-codec-base;4.2.6.Final ...
          [info] Resolving io.netty#netty-codec-base;4.2.6.Final ...
          [info] Resolving io.netty#netty-parent;4.2.6.Final ...
          [info] Resolving io.netty#netty-codec-compression;4.2.6.Final ...
          [info] Resolving io.netty#netty-codec-compression;4.2.6.Final ...
          [info] Resolving io.netty#netty-parent;4.2.6.Final ...
          [info] Resolving io.netty#netty-handler;4.2.6.Final ...
          [info] Resolving io.netty#netty-handler;4.2.6.Final ...
          [info] Resolving io.netty#netty-parent;4.2.6.Final ...
          [info] Resolving io.netty#netty-transport-native-unix-common;4.2.6.Final ...
          [info] Resolving io.netty#netty-transport-native-unix-common;4.2.6.Final ...
          [info] Resolving io.netty#netty-parent;4.2.6.Final ...
          [info] Resolving io.netty#netty-handler-proxy;4.2.6.Final ...
          [info] Resolving io.netty#netty-handler-proxy;4.2.6.Final ...
          [info] Resolving io.netty#netty-parent;4.2.6.Final ...
          [info] Resolving io.netty#netty-codec-socks;4.2.6.Final ...
          [info] Resolving io.netty#netty-codec-socks;4.2.6.Final ...
          [info] Resolving io.netty#netty-parent;4.2.6.Final ...
          [info] Resolving io.netty#netty-transport-native-epoll;4.2.6.Final ...
          [info] Resolving io.netty#netty-transport-native-epoll;4.2.6.Final ...
          [info] Resolving io.netty#netty-parent;4.2.6.Final ...
          [info] Resolving io.netty#netty-transport-classes-epoll;4.2.6.Final ...
          [info] Resolving io.netty#netty-transport-classes-epoll;4.2.6.Final ...
          [info] Resolving io.netty#netty-parent;4.2.6.Final ...
          [info] Resolving io.netty#netty-transport-native-kqueue;4.2.6.Final ...
          [info] Resolving io.netty#netty-transport-native-kqueue;4.2.6.Final ...
          [info] Resolving io.netty#netty-parent;4.2.6.Final ...
          [info] Resolving io.netty#netty-transport-classes-kqueue;4.2.6.Final ...
          [info] Resolving io.netty#netty-transport-classes-kqueue;4.2.6.Final ...
          [info] Resolving io.netty#netty-parent;4.2.6.Final ...
          [info] Resolving io.netty#netty-pkitesting;4.2.6.Final ...
          [info] Resolving io.netty#netty-pkitesting;4.2.6.Final ...
          [info] Resolving io.netty#netty-parent;4.2.6.Final ...
          [info] Resolving org.bouncycastle#bcpkix-jdk18on;1.80 ...
          [info] Resolving org.bouncycastle#bcpkix-jdk18on;1.80 ...
          [info] Resolving org.bouncycastle#bcutil-jdk18on;[1.80,1.81) ...
          [info] Resolving org.bouncycastle#bcutil-jdk18on;[1.80,1.81) ...
          [info] Resolving org.bouncycastle#bcprov-jdk18on;1.80 ...
          [info] Resolving org.bouncycastle#bcprov-jdk18on;1.80 ...
          [info] Resolving org.scala-lang#scala-compiler;2.13.17 ...
          [info] Resolving org.scala-lang#scala-compiler;2.13.17 ...
          [info] Resolving io.github.java-diff-utils#java-diff-utils;4.16 ...
          [info] Resolving io.github.java-diff-utils#java-diff-utils;4.16 ...
          [info] Resolving io.github.java-diff-utils#java-diff-utils-parent;4.16 ...
          [info] Resolving io.github.java-diff-utils#java-diff-utils-parent;4.16 ...
          [info] Resolving org.jline#jline;3.29.0 ...
          [info] Resolving org.jline#jline;3.29.0 ...
          [info] Resolving org.jline#jline-parent;3.29.0 ...
          [info] Resolving org.jline#jline-parent;3.29.0 ...
          [info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.17/scala-library-2.13.17.jar ...
          [info] 	[SUCCESSFUL ] org.scala-lang#scala-library;2.13.17!scala-library.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/dev/zio/zio-http_2.13/3.5.1/zio-http_2.13-3.5.1.jar ...
          [info] 	[SUCCESSFUL ] dev.zio#zio-http_2.13;3.5.1!zio-http_2.13.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.17/scala-reflect-2.13.17.jar ...
          [info] 	[SUCCESSFUL ] org.scala-lang#scala-reflect;2.13.17!scala-reflect.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/dev/zio/zio_2.13/2.1.21/zio_2.13-2.1.21.jar ...
          [info] 	[SUCCESSFUL ] dev.zio#zio_2.13;2.1.21!zio_2.13.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/dev/zio/zio-streams_2.13/2.1.21/zio-streams_2.13-2.1.21.jar ...
          [info] 	[SUCCESSFUL ] dev.zio#zio-streams_2.13;2.1.21!zio-streams_2.13.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/dev/zio/zio-schema_2.13/1.7.4/zio-schema_2.13-1.7.4.jar ...
          [info] 	[SUCCESSFUL ] dev.zio#zio-schema_2.13;1.7.4!zio-schema_2.13.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/dev/zio/zio-schema-json_2.13/1.7.4/zio-schema-json_2.13-1.7.4.jar ...
          [info] 	[SUCCESSFUL ] dev.zio#zio-schema-json_2.13;1.7.4!zio-schema-json_2.13.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/dev/zio/zio-schema-protobuf_2.13/1.7.4/zio-schema-protobuf_2.13-1.7.4.jar ...
          [info] 	[SUCCESSFUL ] dev.zio#zio-schema-protobuf_2.13;1.7.4!zio-schema-protobuf_2.13.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.13/2.13.0/scala-collection-compat_2.13-2.13.0.jar ...
          [info] 	[SUCCESSFUL ] org.scala-lang.modules#scala-collection-compat_2.13;2.13.0!scala-collection-compat_2.13.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/io/netty/netty-codec-http/4.2.6.Final/netty-codec-http-4.2.6.Final.jar ...
          [info] 	[SUCCESSFUL ] io.netty#netty-codec-http;4.2.6.Final!netty-codec-http.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/io/netty/netty-handler-proxy/4.2.6.Final/netty-handler-proxy-4.2.6.Final.jar ...
          [info] 	[SUCCESSFUL ] io.netty#netty-handler-proxy;4.2.6.Final!netty-handler-proxy.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/io/netty/netty-transport-native-epoll/4.2.6.Final/netty-transport-native-epoll-4.2.6.Final-linux-aarch_64.jar ...
          [info] 	[SUCCESSFUL ] io.netty#netty-transport-native-epoll;4.2.6.Final!netty-transport-native-epoll.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/io/netty/netty-transport-native-epoll/4.2.6.Final/netty-transport-native-epoll-4.2.6.Final.jar ...
          [info] 	[SUCCESSFUL ] io.netty#netty-transport-native-epoll;4.2.6.Final!netty-transport-native-epoll.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/io/netty/netty-transport-native-epoll/4.2.6.Final/netty-transport-native-epoll-4.2.6.Final-linux-x86_64.jar ...
          [info] 	[SUCCESSFUL ] io.netty#netty-transport-native-epoll;4.2.6.Final!netty-transport-native-epoll.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/io/netty/netty-transport-native-kqueue/4.2.6.Final/netty-transport-native-kqueue-4.2.6.Final-osx-aarch_64.jar ...
          [info] 	[SUCCESSFUL ] io.netty#netty-transport-native-kqueue;4.2.6.Final!netty-transport-native-kqueue.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/io/netty/netty-transport-native-kqueue/4.2.6.Final/netty-transport-native-kqueue-4.2.6.Final.jar ...
          [info] 	[SUCCESSFUL ] io.netty#netty-transport-native-kqueue;4.2.6.Final!netty-transport-native-kqueue.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/io/netty/netty-transport-native-kqueue/4.2.6.Final/netty-transport-native-kqueue-4.2.6.Final-osx-x86_64.jar ...
          [info] 	[SUCCESSFUL ] io.netty#netty-transport-native-kqueue;4.2.6.Final!netty-transport-native-kqueue.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/io/netty/netty-pkitesting/4.2.6.Final/netty-pkitesting-4.2.6.Final.jar ...
          [info] 	[SUCCESSFUL ] io.netty#netty-pkitesting;4.2.6.Final!netty-pkitesting.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/dev/zio/zio-internal-macros_2.13/2.1.21/zio-internal-macros_2.13-2.1.21.jar ...
          [info] 	[SUCCESSFUL ] dev.zio#zio-internal-macros_2.13;2.1.21!zio-internal-macros_2.13.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/dev/zio/zio-stacktracer_2.13/2.1.21/zio-stacktracer_2.13-2.1.21.jar ...
          [info] 	[SUCCESSFUL ] dev.zio#zio-stacktracer_2.13;2.1.21!zio-stacktracer_2.13.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/dev/zio/izumi-reflect_2.13/3.0.6/izumi-reflect_2.13-3.0.6.jar ...
          [info] 	[SUCCESSFUL ] dev.zio#izumi-reflect_2.13;3.0.6!izumi-reflect_2.13.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/dev/zio/izumi-reflect-thirdparty-boopickle-shaded_2.13/3.0.6/izumi-reflect-thirdparty-boopickle-shaded_2.13-3.0.6.jar ...
          [info] 	[SUCCESSFUL ] dev.zio#izumi-reflect-thirdparty-boopickle-shaded_2.13;3.0.6!izumi-reflect-thirdparty-boopickle-shaded_2.13.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/dev/zio/zio-schema-macros_2.13/1.7.4/zio-schema-macros_2.13-1.7.4.jar ...
          [info] 	[SUCCESSFUL ] dev.zio#zio-schema-macros_2.13;1.7.4!zio-schema-macros_2.13.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/dev/zio/zio-prelude_2.13/1.0.0-RC41/zio-prelude_2.13-1.0.0-RC41.jar ...
          [info] 	[SUCCESSFUL ] dev.zio#zio-prelude_2.13;1.0.0-RC41!zio-prelude_2.13.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/dev/zio/zio-constraintless_2.13/0.3.3/zio-constraintless_2.13-0.3.3.jar ...
          [info] 	[SUCCESSFUL ] dev.zio#zio-constraintless_2.13;0.3.3!zio-constraintless_2.13.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/dev/zio/zio-prelude-macros_2.13/1.0.0-RC41/zio-prelude-macros_2.13-1.0.0-RC41.jar ...
          [info] 	[SUCCESSFUL ] dev.zio#zio-prelude-macros_2.13;1.0.0-RC41!zio-prelude-macros_2.13.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/dev/zio/zio-schema-derivation_2.13/1.7.4/zio-schema-derivation_2.13-1.7.4.jar ...
          [info] 	[SUCCESSFUL ] dev.zio#zio-schema-derivation_2.13;1.7.4!zio-schema-derivation_2.13.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/dev/zio/zio-json_2.13/0.7.44/zio-json_2.13-0.7.44.jar ...
          [info] 	[SUCCESSFUL ] dev.zio#zio-json_2.13;0.7.44!zio-json_2.13.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/com/softwaremill/magnolia1_2/magnolia_2.13/1.1.10/magnolia_2.13-1.1.10.jar ...
          [info] 	[SUCCESSFUL ] com.softwaremill.magnolia1_2#magnolia_2.13;1.1.10!magnolia_2.13.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/io/netty/netty-common/4.2.6.Final/netty-common-4.2.6.Final.jar ...
          [info] 	[SUCCESSFUL ] io.netty#netty-common;4.2.6.Final!netty-common.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/io/netty/netty-buffer/4.2.6.Final/netty-buffer-4.2.6.Final.jar ...
          [info] 	[SUCCESSFUL ] io.netty#netty-buffer;4.2.6.Final!netty-buffer.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/io/netty/netty-transport/4.2.6.Final/netty-transport-4.2.6.Final.jar ...
          [info] 	[SUCCESSFUL ] io.netty#netty-transport;4.2.6.Final!netty-transport.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/io/netty/netty-codec-base/4.2.6.Final/netty-codec-base-4.2.6.Final.jar ...
          [info] 	[SUCCESSFUL ] io.netty#netty-codec-base;4.2.6.Final!netty-codec-base.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/io/netty/netty-codec-compression/4.2.6.Final/netty-codec-compression-4.2.6.Final.jar ...
          [info] 	[SUCCESSFUL ] io.netty#netty-codec-compression;4.2.6.Final!netty-codec-compression.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/io/netty/netty-handler/4.2.6.Final/netty-handler-4.2.6.Final.jar ...
          [info] 	[SUCCESSFUL ] io.netty#netty-handler;4.2.6.Final!netty-handler.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/io/netty/netty-resolver/4.2.6.Final/netty-resolver-4.2.6.Final.jar ...
          [info] 	[SUCCESSFUL ] io.netty#netty-resolver;4.2.6.Final!netty-resolver.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/io/netty/netty-transport-native-unix-common/4.2.6.Final/netty-transport-native-unix-common-4.2.6.Final.jar ...
          [info] 	[SUCCESSFUL ] io.netty#netty-transport-native-unix-common;4.2.6.Final!netty-transport-native-unix-common.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/io/netty/netty-codec-socks/4.2.6.Final/netty-codec-socks-4.2.6.Final.jar ...
          [info] 	[SUCCESSFUL ] io.netty#netty-codec-socks;4.2.6.Final!netty-codec-socks.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/io/netty/netty-transport-classes-epoll/4.2.6.Final/netty-transport-classes-epoll-4.2.6.Final.jar ...
          [info] 	[SUCCESSFUL ] io.netty#netty-transport-classes-epoll;4.2.6.Final!netty-transport-classes-epoll.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/io/netty/netty-transport-classes-kqueue/4.2.6.Final/netty-transport-classes-kqueue-4.2.6.Final.jar ...
          [info] 	[SUCCESSFUL ] io.netty#netty-transport-classes-kqueue;4.2.6.Final!netty-transport-classes-kqueue.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/bouncycastle/bcpkix-jdk18on/1.80/bcpkix-jdk18on-1.80.jar ...
          [info] 	[SUCCESSFUL ] org.bouncycastle#bcpkix-jdk18on;1.80!bcpkix-jdk18on.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk18on/1.80/bcprov-jdk18on-1.80.jar ...
          [info] 	[SUCCESSFUL ] org.bouncycastle#bcprov-jdk18on;1.80!bcprov-jdk18on.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/bouncycastle/bcutil-jdk18on/1.80/bcutil-jdk18on-1.80.jar ...
          [info] 	[SUCCESSFUL ] org.bouncycastle#bcutil-jdk18on;1.80!bcutil-jdk18on.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.17/scala-compiler-2.13.17.jar ...
          [info] 	[SUCCESSFUL ] org.scala-lang#scala-compiler;2.13.17!scala-compiler.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/io/github/java-diff-utils/java-diff-utils/4.16/java-diff-utils-4.16.jar ...
          [info] 	[SUCCESSFUL ] io.github.java-diff-utils#java-diff-utils;4.16!java-diff-utils.jar ($DURATION)
          [info] downloading https://repo1.maven.org/maven2/org/jline/jline/3.29.0/jline-3.29.0-jdk8.jar ...
          [info] 	[SUCCESSFUL ] org.jline#jline;3.29.0!jline.jar ($DURATION)
          [info] Done updating.
          [warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
          [warn]
          [warn] 	* org.bouncycastle:bcprov-jdk18on:1.80 is selected over [1.80,1.81)
          [warn] 	    +- org.bouncycastle:bcutil-jdk18on:1.80               (depends on [1.80,1.81))
          [warn] 	    +- io.netty:netty-pkitesting:4.2.6.Final              (depends on [1.80,1.81))
          [warn]
          [warn] Run 'evicted' to see detailed eviction warnings
          [info] This is sbt 0.13.18
          [info] The current project is {file:/app/}app 0.1-SNAPSHOT
          [info] The current project is built against Scala 2.13.17
          [info] Available Plugins: sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, sbt.plugins.CorePlugin, sbt.plugins.JUnitXmlReportPlugin, sbt.plugins.Giter8TemplatePlugin, com.typesafe.sbt.SbtNativePackager, HerokuBuildpackPlugin
          [info] sbt, sbt plugins, and build definitions are using Scala 2.10.7
        OUTPUT
      end
    end
  end

  it 'makes sbt 0.x available at runtime without native packager' do
    new_default_hatchet_runner('sbt-0.13.18-minimal-no-native-packager').tap do |app|
      app.before_deploy do
        # Override sbt-extra's default for OpenJDK >9 and <17 to use JVMCI. Enabling JVMCI causes non-fatal
        # compile errors that bloat the build log. These compile errors are also non-deterministic so checking
        # against the output will not work reliably. We will eventually remove sbt-extras in PR #291 that will
        # make this configuration unnecessary.
        #
        # See: https://github.com/dwijnand/sbt-extras/issues/344
        app.set_config('JVM_OPTS' => '-XX:+UnlockExperimentalVMOptions -XX:-UseJVMCICompiler')
      end

      app.deploy do
        sbt_about_output = app.run('sbt about')
                              .gsub(/\(\d+ms\)/, '($DURATION)')
                              .gsub(%r{\((\d+kB)/\d+ms\)}, '(\1/$DURATION)')
                              .gsub(/\d+\.\d+ s/, '$DURATION s')
                              .gsub(/\[(info|warn|error|success|debug)\] $/, '[\1]')

        expect(sbt_about_output).to eq(<<~OUTPUT)
          [info] Loading global plugins from /app/.sbt_home/plugins
          [info] Updating {file:/app/.sbt_home/plugins/}global-plugins...
          WARNING: An illegal reflective access operation has occurred
          WARNING: Illegal reflective access by sbt.ivyint.ErrorMessageAuthenticator$ (file:/app/.sbt_home/boot/scala-2.10.7/org.scala-sbt/sbt/0.13.18/ivy-0.13.18.jar) to field java.net.Authenticator.theAuthenticator
          WARNING: Please consider reporting this to the maintainers of sbt.ivyint.ErrorMessageAuthenticator$
          WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
          WARNING: All illegal access operations will be denied in a future release
          [info] Resolving org.scala-lang#scala-library;2.10.7 ...
          [info] Resolving org.scala-sbt#sbt;0.13.18 ...
          [info] Resolving org.scala-sbt#main;0.13.18 ...
          [info] Resolving org.scala-sbt#actions;0.13.18 ...
          [info] Resolving org.scala-sbt#classpath;0.13.18 ...
          [info] Resolving org.scala-lang#scala-compiler;2.10.7 ...
          [info] Resolving org.scala-lang#scala-reflect;2.10.7 ...
          [info] Resolving org.scala-sbt#interface;0.13.18 ...
          [info] Resolving org.scala-sbt#io;0.13.18 ...
          [info] Resolving org.scala-sbt#control;0.13.18 ...
          [info] Resolving org.scala-sbt#launcher-interface;1.0.1 ...
          [info] Resolving org.scala-sbt#completion;0.13.18 ...
          [info] Resolving org.scala-sbt#collections;0.13.18 ...
          [info] Resolving jline#jline;2.14.5 ...
          [info] Resolving org.scala-sbt#api;0.13.18 ...
          [info] Resolving org.scala-sbt#classfile;0.13.18 ...
          [info] Resolving org.scala-sbt#logging;0.13.18 ...
          [info] Resolving org.scala-sbt#process;0.13.18 ...
          [info] Resolving org.scala-sbt#compiler-integration;0.13.18 ...
          [info] Resolving org.scala-sbt#incremental-compiler;0.13.18 ...
          [info] Resolving org.scala-sbt#relation;0.13.18 ...
          [info] Resolving org.scala-sbt#compile;0.13.18 ...
          [info] Resolving org.scala-sbt#persist;0.13.18 ...
          [info] Resolving org.scala-tools.sbinary#sbinary_2.10;0.4.2 ...
          [info] Resolving org.scala-sbt#compiler-ivy-integration;0.13.18 ...
          [info] Resolving org.scala-sbt#ivy;0.13.18 ...
          [info] Resolving org.scala-sbt#cross;0.13.18 ...
          [info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-b18f59ea3bc914a297bb6f1a4f7fb0ace399e310 ...
          [info] Resolving com.jcraft#jsch;0.1.50 ...
          [info] Resolving org.scala-sbt#serialization_2.10;0.1.2 ...
          [info] Resolving org.scala-lang.modules#scala-pickling_2.10;0.10.1 ...
          [info] Resolving org.scalamacros#quasiquotes_2.10;2.0.1 ...
          [info] Resolving org.json4s#json4s-core_2.10;3.2.10 ...
          [info] Resolving org.json4s#json4s-ast_2.10;3.2.10 ...
          [info] Resolving com.thoughtworks.paranamer#paranamer;2.6 ...
          [info] Resolving org.spire-math#jawn-parser_2.10;0.6.0 ...
          [info] Resolving org.spire-math#json4s-support_2.10;0.6.0 ...
          [info] Resolving org.scala-sbt#run;0.13.18 ...
          [info] Resolving org.scala-sbt#task-system;0.13.18 ...
          [info] Resolving org.scala-sbt#tasks;0.13.18 ...
          [info] Resolving org.scala-sbt#tracking;0.13.18 ...
          [info] Resolving org.scala-sbt#cache;0.13.18 ...
          [info] Resolving org.scala-sbt#testing;0.13.18 ...
          [info] Resolving org.scala-sbt#test-agent;0.13.18 ...
          [info] Resolving org.scala-sbt#test-interface;1.0 ...
          [info] Resolving org.scala-sbt#main-settings;0.13.18 ...
          [info] Resolving org.scala-sbt#apply-macro;0.13.18 ...
          [info] Resolving org.scala-sbt#command;0.13.18 ...
          [info] Resolving org.scala-sbt#template-resolver;0.1 ...
          [info] Resolving org.scala-sbt#logic;0.13.18 ...
          [info] Resolving org.scala-sbt#compiler-interface;0.13.18 ...
          [info] Resolving org.scala-lang#jline;2.10.7 ...
          [info] Resolving org.fusesource.jansi#jansi;1.4 ...
          [info] Done updating.
          [info] Compiling 1 Scala source to /app/.sbt_home/plugins/target/scala-2.10/sbt-0.13/classes...
          [info] Loading project definition from /app/project
          [info] Updating {file:/app/project/}app-build...
          [info] Resolving org.scala-sbt#global-plugins;0.0 ...
          [info] Resolving org.scala-lang#scala-library;2.10.7 ...
          [info] Resolving org.scala-sbt#sbt;0.13.18 ...
          [info] Resolving org.scala-sbt#main;0.13.18 ...
          [info] Resolving org.scala-sbt#actions;0.13.18 ...
          [info] Resolving org.scala-sbt#classpath;0.13.18 ...
          [info] Resolving org.scala-lang#scala-compiler;2.10.7 ...
          [info] Resolving org.scala-lang#scala-reflect;2.10.7 ...
          [info] Resolving org.scala-sbt#interface;0.13.18 ...
          [info] Resolving org.scala-sbt#io;0.13.18 ...
          [info] Resolving org.scala-sbt#control;0.13.18 ...
          [info] Resolving org.scala-sbt#launcher-interface;1.0.1 ...
          [info] Resolving org.scala-sbt#completion;0.13.18 ...
          [info] Resolving org.scala-sbt#collections;0.13.18 ...
          [info] Resolving jline#jline;2.14.5 ...
          [info] Resolving org.scala-sbt#api;0.13.18 ...
          [info] Resolving org.scala-sbt#classfile;0.13.18 ...
          [info] Resolving org.scala-sbt#logging;0.13.18 ...
          [info] Resolving org.scala-sbt#process;0.13.18 ...
          [info] Resolving org.scala-sbt#compiler-integration;0.13.18 ...
          [info] Resolving org.scala-sbt#incremental-compiler;0.13.18 ...
          [info] Resolving org.scala-sbt#relation;0.13.18 ...
          [info] Resolving org.scala-sbt#compile;0.13.18 ...
          [info] Resolving org.scala-sbt#persist;0.13.18 ...
          [info] Resolving org.scala-tools.sbinary#sbinary_2.10;0.4.2 ...
          [info] Resolving org.scala-sbt#compiler-ivy-integration;0.13.18 ...
          [info] Resolving org.scala-sbt#ivy;0.13.18 ...
          [info] Resolving org.scala-sbt#cross;0.13.18 ...
          [info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-b18f59ea3bc914a297bb6f1a4f7fb0ace399e310 ...
          [info] Resolving com.jcraft#jsch;0.1.50 ...
          [info] Resolving org.scala-sbt#serialization_2.10;0.1.2 ...
          [info] Resolving org.scala-lang.modules#scala-pickling_2.10;0.10.1 ...
          [info] Resolving org.scalamacros#quasiquotes_2.10;2.0.1 ...
          [info] Resolving org.json4s#json4s-core_2.10;3.2.10 ...
          [info] Resolving org.json4s#json4s-ast_2.10;3.2.10 ...
          [info] Resolving com.thoughtworks.paranamer#paranamer;2.6 ...
          [info] Resolving org.spire-math#jawn-parser_2.10;0.6.0 ...
          [info] Resolving org.spire-math#json4s-support_2.10;0.6.0 ...
          [info] Resolving org.scala-sbt#run;0.13.18 ...
          [info] Resolving org.scala-sbt#task-system;0.13.18 ...
          [info] Resolving org.scala-sbt#tasks;0.13.18 ...
          [info] Resolving org.scala-sbt#tracking;0.13.18 ...
          [info] Resolving org.scala-sbt#cache;0.13.18 ...
          [info] Resolving org.scala-sbt#testing;0.13.18 ...
          [info] Resolving org.scala-sbt#test-agent;0.13.18 ...
          [info] Resolving org.scala-sbt#test-interface;1.0 ...
          [info] Resolving org.scala-sbt#main-settings;0.13.18 ...
          [info] Resolving org.scala-sbt#apply-macro;0.13.18 ...
          [info] Resolving org.scala-sbt#command;0.13.18 ...
          [info] Resolving org.scala-sbt#template-resolver;0.1 ...
          [info] Resolving org.scala-sbt#logic;0.13.18 ...
          [info] Resolving org.scala-sbt#compiler-interface;0.13.18 ...
          [info] Resolving org.scala-lang#jline;2.10.7 ...
          [info] Resolving org.fusesource.jansi#jansi;1.4 ...
          [info] Done updating.
          [info] Set current project to sbt-0.13.18-minimal-no-native-packager (in build file:/app/)
          [info] Updating {file:/app/}app...
          [info] Resolving org.scala-lang#scala-library;2.13.17 ...
          [info] Resolving dev.zio#zio-http_2.13;3.5.1 ...
          [info] Resolving org.scala-lang#scala-reflect;2.13.17 ...
          [info] Resolving dev.zio#zio_2.13;2.1.21 ...
          [info] Resolving dev.zio#zio-internal-macros_2.13;2.1.21 ...
          [info] Resolving dev.zio#zio-stacktracer_2.13;2.1.21 ...
          [info] Resolving dev.zio#izumi-reflect_2.13;3.0.6 ...
          [info] Resolving dev.zio#izumi-reflect-thirdparty-boopickle-shaded_2.13;3.0.6 ...
          [info] Resolving org.scala-lang.modules#scala-collection-compat_2.13;2.13.0 ...
          [info] Resolving dev.zio#zio-streams_2.13;2.1.21 ...
          [info] Resolving dev.zio#zio-schema_2.13;1.7.4 ...
          [info] Resolving dev.zio#zio-schema-macros_2.13;1.7.4 ...
          [info] Resolving dev.zio#zio-prelude_2.13;1.0.0-RC41 ...
          [info] Resolving dev.zio#zio-prelude-macros_2.13;1.0.0-RC41 ...
          [info] Resolving dev.zio#zio-constraintless_2.13;0.3.3 ...
          [info] Resolving dev.zio#zio-schema-json_2.13;1.7.4 ...
          [info] Resolving dev.zio#zio-schema-derivation_2.13;1.7.4 ...
          [info] Resolving dev.zio#zio-json_2.13;0.7.44 ...
          [info] Resolving com.softwaremill.magnolia1_2#magnolia_2.13;1.1.10 ...
          [info] Resolving dev.zio#zio-schema-protobuf_2.13;1.7.4 ...
          [info] Resolving io.netty#netty-codec-http;4.2.6.Final ...
          [info] Resolving io.netty#netty-common;4.2.6.Final ...
          [info] Resolving io.netty#netty-buffer;4.2.6.Final ...
          [info] Resolving io.netty#netty-transport;4.2.6.Final ...
          [info] Resolving io.netty#netty-resolver;4.2.6.Final ...
          [info] Resolving io.netty#netty-codec-base;4.2.6.Final ...
          [info] Resolving io.netty#netty-codec-compression;4.2.6.Final ...
          [info] Resolving io.netty#netty-handler;4.2.6.Final ...
          [info] Resolving io.netty#netty-transport-native-unix-common;4.2.6.Final ...
          [info] Resolving io.netty#netty-handler-proxy;4.2.6.Final ...
          [info] Resolving io.netty#netty-codec-socks;4.2.6.Final ...
          [info] Resolving io.netty#netty-transport-native-epoll;4.2.6.Final ...
          [info] Resolving io.netty#netty-transport-classes-epoll;4.2.6.Final ...
          [info] Resolving io.netty#netty-transport-native-kqueue;4.2.6.Final ...
          [info] Resolving io.netty#netty-transport-classes-kqueue;4.2.6.Final ...
          [info] Resolving io.netty#netty-pkitesting;4.2.6.Final ...
          [info] Resolving org.bouncycastle#bcpkix-jdk18on;1.80 ...
          [info] Resolving org.bouncycastle#bcutil-jdk18on;[1.80,1.81) ...
          [info] Resolving org.bouncycastle#bcutil-jdk18on;[1.80,1.81) ...
          [info] Resolving org.bouncycastle#bcprov-jdk18on;1.80 ...
          [info] Resolving org.scala-lang#scala-compiler;2.13.17 ...
          [info] Resolving io.github.java-diff-utils#java-diff-utils;4.16 ...
          [info] Resolving org.jline#jline;3.29.0 ...
          [info] Done updating.
          [warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
          [warn]
          [warn] 	* org.bouncycastle:bcprov-jdk18on:1.80 is selected over [1.80,1.81)
          [warn] 	    +- org.bouncycastle:bcutil-jdk18on:1.80               (depends on [1.80,1.81))
          [warn] 	    +- io.netty:netty-pkitesting:4.2.6.Final              (depends on [1.80,1.81))
          [warn]
          [warn] Run 'evicted' to see detailed eviction warnings
          [info] This is sbt 0.13.18
          [info] The current project is {file:/app/}app 0.1-SNAPSHOT
          [info] The current project is built against Scala 2.13.17
          [info] Available Plugins: sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, sbt.plugins.CorePlugin, sbt.plugins.JUnitXmlReportPlugin, sbt.plugins.Giter8TemplatePlugin, HerokuBuildpackPlugin
          [info] sbt, sbt plugins, and build definitions are using Scala 2.10.7
        OUTPUT
      end
    end
  end
end
